// SPDX-License-Identifier: GPL-2.0-only
#ifndef PKM_LCS_KUNIT_COMMON_H
#define PKM_LCS_KUNIT_COMMON_H

/* Generated by tools split of the monolithic kunit.c — see git log. */

// SPDX-License-Identifier: GPL-2.0-only

#include <crypto/sha2.h>

#include <kunit/test.h>

#include <linux/anon_inodes.h>

#include <linux/completion.h>

#include <linux/delay.h>

#include <linux/err.h>

#include <linux/errno.h>

#include <linux/fcntl.h>

#include <linux/fdtable.h>

#include <linux/file.h>

#include <linux/fs.h>

#include <linux/kthread.h>

#include <linux/poll.h>

#include <linux/sched/task.h>

#include <linux/slab.h>

#include <linux/string.h>

#include <linux/task_work.h>

#include <linux/uio.h>

#include <linux/unaligned.h>


#include <pkm/token.h>


#include "../kacs/token_runtime.h"

#include "../kmes/kmes.h"

#include "key_fd.h"

#include "rsi.h"

#include "source_device.h"

#include "transaction_fd.h"


extern size_t lcs_rust_kunit_probe(void);

extern int lcs_rust_write_backup_key_record_frame(
	u8 *dst, size_t dst_len, const u8 *guid, u8 volatile_key, u8 symlink,
	const u8 *security_descriptor, size_t security_descriptor_len,
	s64 last_write_time_ns, size_t *written_out);

extern int lcs_rust_write_backup_layer_manifest_record_frame(
	u8 *dst, size_t dst_len, const struct pkm_lcs_runtime_limits *limits,
	const u8 *name, size_t name_len, u32 precedence, u8 enabled,
	const u8 *owner_sid, size_t owner_sid_len, size_t *written_out);


struct pkm_lcs_kunit_audit_caller_summary {
	u8 effective_token_guid[16];
	u8 true_token_guid[16];
	u8 process_guid[16];
	const u8 *user_sid;
	size_t user_sid_len;
	u64 authentication_id;
	u64 token_id;
	u32 token_type;
	u32 impersonation_level;
	u32 integrity_level;
};


extern int lcs_rust_key_open_audit_payload(
	const struct pkm_lcs_kunit_audit_caller_summary *caller,
	const u8 key_guid[16], u32 requested_access, u32 granted_access,
	u8 allowed, u32 sacl_match_flags, u8 *output, size_t output_len,
	size_t *written_out);

extern int lcs_rust_backup_start_audit_payload(
	const struct pkm_lcs_kunit_audit_caller_summary *caller,
	const u8 key_guid[16], s32 output_fd, u8 *output, size_t output_len,
	size_t *written_out);

extern int lcs_rust_backup_complete_audit_payload(
	const struct pkm_lcs_kunit_audit_caller_summary *caller,
	const u8 key_guid[16], u32 result_errno, u8 *output,
	size_t output_len, size_t *written_out);

extern int lcs_rust_restore_start_audit_payload(
	const struct pkm_lcs_kunit_audit_caller_summary *caller,
	const u8 key_guid[16], s32 input_fd, u8 *output, size_t output_len,
	size_t *written_out);

extern int lcs_rust_restore_complete_audit_payload(
	const struct pkm_lcs_kunit_audit_caller_summary *caller,
	const u8 key_guid[16], u32 result_errno, u8 *output,
	size_t output_len, size_t *written_out);


void pkm_lcs_kunit_build_status_response(struct kunit *test, u8 *frame,
						size_t frame_len,
						u64 request_id,
						u16 request_op, u32 status,
						size_t *built_len);


struct pkm_lcs_kunit_usercopy_ctx {
	const void *fault_src;
	const void *fault_dst;
	const void *fault_strlen_src;
	const void *unterminated_src;
	unsigned int reads;
	unsigned int writes;
	unsigned int strnlens;
};


struct pkm_lcs_kunit_walk_source_step {
	const char *expected_child;
	const char *layer_name;
	const u8 *guid;
	const u8 *sd;
	size_t sd_len;
	u64 sequence;
	const char *second_layer_name;
	const u8 *second_guid;
	const u8 *second_sd;
	size_t second_sd_len;
	u64 second_sequence;
	bool empty;
	bool hidden;
	bool symlink;
	bool include_second_entry;
	bool second_hidden;
	bool second_symlink;
};


struct pkm_lcs_kunit_walk_source_script {
	struct file *file;
	const struct pkm_lcs_kunit_walk_source_step *steps;
	u64 expected_txn_id;
	u32 step_count;
	bool reset_runtime_limits_before_response;
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_read_key_source_script {
	struct file *file;
	const u8 *expected_guid;
	const char *name;
	const u8 *parent_guid;
	const u8 *sd;
	size_t sd_len;
	u64 last_write_time;
	u64 expected_txn_id;
	u32 status;
	bool volatile_key;
	bool symlink;
	bool reset_runtime_limits_before_response;
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_transaction_source_script {
	struct file *file;
	struct pkm_lcs_kunit_delete_key_ioctl_source_script
		*delete_key_lookup_after;
	struct pkm_lcs_kunit_walk_source_script *hide_key_lookup_after;
	struct pkm_lcs_kunit_delete_layer_source_script
		*delete_layer_after;
	bool expect_layer_refresh;
	bool expect_delete_layer;
	struct pkm_lcs_kunit_layer_metadata_refresh_source_script
		*layer_refresh_after;
	u16 expected_op_code;
	u32 expected_mode;
	u32 status;
	u64 expected_header_txn_id;
	u64 expected_payload_txn_id;
	u32 reads;
	u32 writes;
	bool reset_runtime_limits_before_response;
	int result;
};


struct pkm_lcs_kunit_backup_snapshot_source_script {
	struct file *file;
	u32 begin_status;
	u32 abort_status;
	u64 transaction_id;
	u32 reads;
	u32 writes;
	bool saw_abort;
	bool expect_export_reads;
	bool expect_child_export_reads;
	bool expect_grandchild_export_reads;
	bool nonempty_child_response;
	bool hidden_child_response;
	bool root_value_response;
	bool child_value_response;
	bool grandchild_value_response;
	bool grandchild_response;
	bool cycle_child_response;
	int result;
};


struct pkm_lcs_kunit_backup_call_script {
	long key_fd;
	const void *token;
	struct reg_backup_args args;
	long result;
};


struct pkm_lcs_kunit_flush_source_script {
	struct file *file;
	const char *expected_hive_name;
	u32 status;
	bool extra_response_payload;
	bool reset_runtime_limits_before_response;
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_drop_key_source_script {
	struct file *file;
	const u8 *expected_guid;
	u64 expected_txn_id;
	u32 status;
	bool extra_response_payload;
	bool reset_runtime_limits_before_response;
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_delete_layer_source_script {
	struct file *file;
	const char *expected_layer_name;
	const u8 *orphaned_guid_a;
	const u8 *orphaned_guid_b;
	u64 expected_abort_txn_id;
	u32 status;
	u32 orphaned_guid_count;
	bool extra_response_payload;
	bool abort_before_delete_observed;
	bool reset_runtime_limits_before_response;
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_path_entry_source_script {
	struct file *file;
	const u8 *expected_parent_guid;
	const char *expected_child_name;
	const char *expected_layer_name;
	u64 expected_txn_id;
	u64 expected_sequence;
	u16 expected_op_code;
	u32 status;
	bool extra_response_payload;
	u32 reads;
	u32 writes;
	int result;
};


void pkm_lcs_kunit_append_set_value_log_for_layer(
	struct kunit *test, int fd, const u8 root_guid[16],
	const char *layer, u64 sequence);


struct pkm_lcs_kunit_set_security_source_script {
	struct file *file;
	struct pkm_lcs_kunit_transaction_source_script begin;
	const u8 *expected_guid;
	const u8 *existing_sd;
	size_t existing_sd_len;
	const u8 *expected_merged_sd;
	size_t expected_merged_sd_len;
	u64 expected_txn_id;
	u64 observed_last_write_time;
	u32 reads;
	u32 writes;
	bool expect_begin;
	int result;
};


struct pkm_lcs_kunit_query_values_source_script {
	struct file *file;
	const u8 *expected_guid;
	const char *expected_value_name;
	const char *response_value_name;
	const char *layer_name;
	const u8 *data;
	size_t data_len;
	u32 value_type;
	u64 sequence;
	const char *second_response_value_name;
	const char *second_layer_name;
	const u8 *second_data;
	size_t second_data_len;
	u32 second_value_type;
	u64 second_sequence;
	u64 expected_txn_id;
	bool query_all;
	bool empty;
	bool include_blanket;
	bool include_second_value;
	const char *blanket_layer_name;
	u64 blanket_sequence;
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_set_value_source_script {
	struct file *file;
	const u8 *expected_guid;
	const char *expected_value_name;
	const char *expected_layer_name;
	const u8 *expected_data;
	size_t expected_data_len;
	u32 expected_value_type;
	u64 expected_txn_id;
	u64 expected_sequence;
	u64 expected_expected_sequence;
	u32 status;
	bool extra_response_payload;
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_delete_value_source_script {
	struct file *file;
	const u8 *expected_guid;
	const char *expected_value_name;
	const char *expected_layer_name;
	u64 expected_txn_id;
	u32 status;
	bool extra_response_payload;
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_blanket_tombstone_source_script {
	struct file *file;
	const u8 *expected_guid;
	const char *expected_layer_name;
	u64 expected_txn_id;
	u64 expected_sequence;
	u32 status;
	bool expected_set;
	bool extra_response_payload;
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_set_value_ioctl_source_script {
	struct file *file;
	struct pkm_lcs_kunit_transaction_source_script begin;
	const u8 *expected_guid;
	const char *expected_value_name;
	const char *expected_layer_name;
	const u8 *expected_data;
	size_t expected_data_len;
	u64 expected_query_txn_id;
	u64 expected_txn_id;
	u32 expected_value_type;
	u64 expected_sequence;
	u64 expected_expected_sequence;
	u32 set_value_status;
	u64 observed_last_write_time;
	u32 reads;
	u32 writes;
	bool expect_begin;
	bool expect_layer_refresh;
	const char *refresh_layer_name;
	const u8 *refresh_sd;
	size_t refresh_sd_len;
	u32 refresh_precedence;
	u32 refresh_enabled;
	bool refresh_precedence_present;
	bool refresh_enabled_present;
	int result;
};


struct pkm_lcs_kunit_layer_metadata_refresh_source_script {
	struct file *file;
	const u8 *expected_guid;
	const char *name;
	const u8 *sd;
	size_t sd_len;
	u32 precedence;
	u32 enabled;
	const u8 *owner_sid;
	size_t owner_sid_len;
	bool precedence_present;
	bool enabled_present;
	bool owner_present;
	bool stop_after_read_key;
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_layer_create_watch_source_script {
	struct pkm_lcs_kunit_walk_source_script lookup;
	struct pkm_lcs_kunit_layer_metadata_refresh_source_script refresh;
	bool expect_refresh;
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_set_security_layer_refresh_source_script {
	struct file *file;
	struct pkm_lcs_kunit_set_security_source_script set_security;
	struct pkm_lcs_kunit_layer_metadata_refresh_source_script refresh;
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_delete_value_ioctl_source_script {
	struct file *file;
	struct pkm_lcs_kunit_transaction_source_script begin;
	const u8 *expected_guid;
	const char *expected_value_name;
	const char *expected_layer_name;
	u64 expected_before_query_txn_id;
	u64 expected_after_query_txn_id;
	u64 expected_txn_id;
	const u8 *before_data;
	size_t before_data_len;
	const char *before_layer_name;
	u32 before_value_type;
	u64 before_sequence;
	bool before_found;
	const u8 *after_data;
	size_t after_data_len;
	const char *after_layer_name;
	u32 after_value_type;
	u64 after_sequence;
	bool after_found;
	u32 delete_status;
	u64 observed_last_write_time;
	u32 reads;
	u32 writes;
	bool expect_begin;
	int result;
};


struct pkm_lcs_kunit_blanket_tombstone_ioctl_source_script {
	struct file *file;
	struct pkm_lcs_kunit_transaction_source_script begin;
	const u8 *expected_guid;
	const char *expected_value_name;
	const char *expected_layer_name;
	u64 expected_before_query_txn_id;
	u64 expected_after_query_txn_id;
	u64 expected_txn_id;
	const u8 *before_data;
	size_t before_data_len;
	const char *before_value_layer_name;
	u32 before_value_type;
	u64 before_value_sequence;
	bool before_value_found;
	bool before_blanket_found;
	u64 before_blanket_sequence;
	const u8 *after_data;
	size_t after_data_len;
	const char *after_value_layer_name;
	u32 after_value_type;
	u64 after_value_sequence;
	bool after_value_found;
	bool after_blanket_found;
	u64 after_blanket_sequence;
	u64 expected_sequence;
	u32 blanket_status;
	u64 observed_last_write_time;
	u32 reads;
	u32 writes;
	bool expected_set;
	bool expect_begin;
	int result;
};


struct pkm_lcs_kunit_delete_key_ioctl_source_script {
	struct file *file;
	struct pkm_lcs_kunit_transaction_source_script begin;
	struct pkm_lcs_kunit_delete_layer_source_script delete_layer;
	const u8 *expected_parent_guid;
	const u8 *expected_key_guid;
	const char *expected_child_name;
	const char *expected_layer_name;
	const u8 *visible_child_guid;
	const char *visible_child_name;
	const char *visible_child_layer_name;
	const u8 *remaining_guid;
	u64 expected_txn_id;
	u32 delete_status;
	u64 observed_parent_last_write_time;
	bool remaining_path_found;
	bool expect_begin;
	bool expect_delete_layer;
	bool skip_orphan_lookup;
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_enum_children_source_script {
	struct file *file;
	const u8 *expected_parent_guid;
	const char *child_name;
	const char *layer_name;
	const u8 *child_guid;
	u64 sequence;
	const char *second_child_name;
	const char *second_layer_name;
	const u8 *second_child_guid;
	u64 second_sequence;
	u64 expected_txn_id;
	u32 repeated_child_count;
	bool check_txn_id;
	bool empty;
	bool hidden;
	bool include_second_entry;
	bool second_hidden;
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_layer_metadata_refresh_all_source_script {
	struct file *file;
	struct pkm_lcs_kunit_enum_children_source_script enum_children;
	struct pkm_lcs_kunit_layer_metadata_refresh_source_script refresh;
	bool expect_refresh;
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_source_bootstrap_source_script {
	struct file *file;
	struct pkm_lcs_kunit_walk_source_script self_config_walk;
	struct pkm_lcs_kunit_query_values_source_script self_config_query;
	struct pkm_lcs_kunit_walk_source_script kmes_walk;
	struct pkm_lcs_kunit_query_values_source_script kmes_query;
	struct pkm_lcs_kunit_walk_source_script layers_walk;
	struct pkm_lcs_kunit_layer_metadata_refresh_all_source_script layers_refresh;
	bool expect_kmes_query;
	bool expect_layers_refresh;
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_symlink_follow_source_script {
	struct file *file;
	struct pkm_lcs_kunit_walk_source_step link_step;
	struct pkm_lcs_kunit_walk_source_step target_step;
	const u8 *target_data;
	size_t target_data_len;
	u32 target_value_type;
	bool expect_target_lookup;
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_hide_key_ioctl_source_script {
	struct file *file;
	struct pkm_lcs_kunit_transaction_source_script begin;
	struct pkm_lcs_kunit_path_entry_source_script hide;
	struct pkm_lcs_kunit_walk_source_script post_lookup;
	bool expect_begin;
	bool expect_post_lookup;
	u32 reads;
	u32 writes;
	int result;
};


enum pkm_lcs_kunit_symlink_sequence_op_code {
	PKM_LCS_KUNIT_SYMLINK_SEQ_LOOKUP = 1,
	PKM_LCS_KUNIT_SYMLINK_SEQ_QUERY_DEFAULT = 2,
	PKM_LCS_KUNIT_SYMLINK_SEQ_READ_KEY = 3,
	PKM_LCS_KUNIT_SYMLINK_SEQ_ENUM_CHILDREN = 4,
};


struct pkm_lcs_kunit_symlink_sequence_op {
	enum pkm_lcs_kunit_symlink_sequence_op_code op;
	const struct pkm_lcs_kunit_walk_source_step *lookup_step;
	const struct pkm_lcs_kunit_read_key_source_script *read_key;
	const struct pkm_lcs_kunit_enum_children_source_script *enum_children;
	const u8 *query_guid;
	const u8 *query_data;
	size_t query_data_len;
	const char *query_layer_name;
	const u8 *second_query_data;
	size_t second_query_data_len;
	const char *second_query_layer_name;
	u32 query_value_type;
	u32 second_query_value_type;
	u64 query_sequence;
	u64 second_query_sequence;
	u64 expected_txn_id;
	bool query_all;
	bool include_second_query_value;
};


struct pkm_lcs_kunit_symlink_sequence_source_script {
	struct file *file;
	const struct pkm_lcs_kunit_symlink_sequence_op *ops;
	u32 op_count;
	u32 reset_limits_after_write_index;
	u32 reads;
	u32 writes;
	bool reset_limits_after_write;
	int result;
};


struct pkm_lcs_kunit_create_source_script {
	struct file *file;
	const u8 *parent_guid;
	const u8 *child_guid;
	const char *child_name;
	const char *layer_name;
	const u8 *sd;
	size_t sd_len;
	u64 expected_sequence;
	u64 expected_txn_id;
	u32 entry_status;
	u32 key_status;
	bool expect_key_request;
	bool volatile_key;
	bool symlink;
	bool allow_any_sd;
	bool allow_any_child_guid;
	u8 captured_child_guid[RSI_GUID_SIZE];
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_create_layer_refresh_source_script {
	struct file *file;
	struct pkm_lcs_kunit_create_source_script create;
	struct pkm_lcs_kunit_layer_metadata_refresh_source_script refresh;
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_read_then_create_source_script {
	struct file *file;
	struct pkm_lcs_kunit_read_key_source_script read_key;
	struct pkm_lcs_kunit_create_source_script create;
	u32 reads;
	u32 writes;
	bool skip_read_key;
	int result;
};


struct pkm_lcs_kunit_walk_then_read_source_script {
	struct file *file;
	struct pkm_lcs_kunit_walk_source_script walk;
	struct pkm_lcs_kunit_read_key_source_script read_key;
	u32 reads;
	u32 writes;
	int result;
};


struct pkm_lcs_kunit_walk_then_query_values_source_script {
	struct file *file;
	struct pkm_lcs_kunit_walk_source_script walk;
	struct pkm_lcs_kunit_query_values_source_script query;
	u32 reads;
	u32 writes;
	bool expect_query;
	int result;
};


void pkm_lcs_kunit_setup_registered_source(struct kunit *test,
						  struct file *file,
						  const void **token_out);

void pkm_lcs_kunit_flush_deferred_key_fd_release(void);

struct task_struct *pkm_lcs_kunit_kthread_run(int (*threadfn)(void *),
						     void *data,
						     const char *name);

int pkm_lcs_kunit_kthread_stop(struct task_struct *task);

int pkm_lcs_kunit_walk_source_thread(void *raw_script);

int pkm_lcs_kunit_walk_then_read_source_thread(void *raw_script);

int
pkm_lcs_kunit_walk_then_query_values_source_thread(void *raw_script);

int pkm_lcs_kunit_read_key_source_thread(void *raw_script);

int pkm_lcs_kunit_set_security_source_thread(void *raw_script);

int pkm_lcs_kunit_query_values_source_thread(void *raw_script);

int pkm_lcs_kunit_set_value_source_thread(void *raw_script);

int pkm_lcs_kunit_delete_value_source_thread(void *raw_script);

int pkm_lcs_kunit_blanket_tombstone_source_thread(void *raw_script);

int pkm_lcs_kunit_set_value_ioctl_source_thread(void *raw_script);

int pkm_lcs_kunit_layer_metadata_refresh_source_thread(void *raw_script);

int pkm_lcs_kunit_layer_create_watch_source_thread(void *raw_script);

int pkm_lcs_kunit_delete_value_ioctl_source_thread(void *raw_script);

int
pkm_lcs_kunit_blanket_tombstone_ioctl_source_thread(void *raw_script);

int pkm_lcs_kunit_delete_key_ioctl_source_thread(void *raw_script);

int pkm_lcs_kunit_hide_key_ioctl_source_thread(void *raw_script);

int pkm_lcs_kunit_enum_children_source_thread(void *raw_script);

int
pkm_lcs_kunit_layer_metadata_refresh_all_source_thread(void *raw_script);

int pkm_lcs_kunit_source_bootstrap_source_thread(void *raw_script);

int pkm_lcs_kunit_symlink_follow_source_thread(void *raw_script);

int pkm_lcs_kunit_symlink_sequence_source_thread(void *raw_script);

int pkm_lcs_kunit_create_source_thread(void *raw_script);

int pkm_lcs_kunit_create_source_expect_entry_request(
	struct pkm_lcs_kunit_create_source_script *script, const u8 *request,
	size_t request_len, u64 *request_id);

int pkm_lcs_kunit_create_source_expect_key_request(
	struct pkm_lcs_kunit_create_source_script *script, const u8 *request,
	size_t request_len, u64 *request_id);

int pkm_lcs_kunit_transaction_source_thread(void *data);

int pkm_lcs_kunit_flush_source_thread(void *data);

int pkm_lcs_kunit_drop_key_source_thread(void *data);

int pkm_lcs_kunit_delete_layer_source_thread(void *data);

int pkm_lcs_kunit_path_entry_source_thread(void *data);

int pkm_lcs_kunit_read_key_source_build_response(
	const struct pkm_lcs_kunit_read_key_source_script *script,
	u64 request_id, u8 *response, size_t response_len, size_t *built_len);

int pkm_lcs_kunit_enum_children_source_build_response(
	const struct pkm_lcs_kunit_enum_children_source_script *script,
	u64 request_id, u8 *response, size_t response_len, size_t *built_len);

int pkm_lcs_kunit_walk_source_append(void *dst, size_t dst_len,
					    size_t *offset, const void *src,
					    size_t src_len);

int pkm_lcs_kunit_walk_source_append_u8(u8 *dst, size_t dst_len,
					       size_t *offset, u8 value);

int pkm_lcs_kunit_walk_source_append_u32(u8 *dst, size_t dst_len,
						size_t *offset, u32 value);

int pkm_lcs_kunit_walk_source_append_u64(u8 *dst, size_t dst_len,
						size_t *offset, u64 value);

int pkm_lcs_kunit_walk_source_append_len_prefixed(
	u8 *dst, size_t dst_len, size_t *offset, const void *src,
	size_t src_len);

void pkm_lcs_kunit_expect_drop_key_request(
	struct kunit *test, struct file *file,
	const u8 guid[PKM_LCS_GUID_BYTES]);


struct pkm_lcs_kunit_backup_output_file {
	u8 data[1024];
	size_t len;
};


struct pkm_lcs_kunit_restore_input_file {
	u8 data[512];
	size_t len;
};


void pkm_lcs_kunit_build_register_args(
	struct reg_src_register_args *args, struct reg_src_hive_entry *hive,
	const char *name, u8 root_guid_first, u64 max_sequence);


struct pkm_lcs_kunit_self_config_default {
	const char *name;
	u32 value;
};


long pkm_lcs_kunit_publish_key_fd_with_depth(u32 depth);


struct pkm_lcs_kunit_restore_layer_record {
	const char *name;
	u32 precedence;
	u8 enabled;
	const u8 *owner_sid;
	size_t owner_sid_len;
};


struct pkm_lcs_kunit_restore_data_record {
	u16 record_type;
	const char *layer_name;
	const u8 *parent_guid;
	const u8 *child_guid;
	const u8 *key_guid;
	const u8 *value_data;
	const char *child_name;
	const char *value_name;
	size_t value_data_len;
	u32 value_type;
	bool before_key;
	bool hidden;
};


int pkm_lcs_kunit_restore_stream_build_with_root_keys(
	struct pkm_lcs_kunit_restore_input_file *input, bool include_unknown,
	u32 root_key_count, bool root_volatile, bool root_symlink);


void pkm_lcs_kunit_expect_source_validation_audit(
	struct kunit *test, const char *validation_class,
	const u8 key_guid[RSI_GUID_SIZE]);


struct pkm_lcs_kunit_restore_txn_source_script {
	struct file *file;
	struct pkm_lcs_kunit_read_key_source_script read_key;
	struct pkm_lcs_kunit_enum_children_source_script enum_children;
	struct pkm_lcs_kunit_path_entry_source_script delete_entry;
	struct pkm_lcs_kunit_enum_children_source_script child_enum_children;
	struct pkm_lcs_kunit_path_entry_source_script child_delete_entry;
	struct pkm_lcs_kunit_enum_children_source_script grandchild_enum_children;
	struct pkm_lcs_kunit_query_values_source_script grandchild_query_values;
	struct pkm_lcs_kunit_drop_key_source_script grandchild_drop_key;
	struct pkm_lcs_kunit_query_values_source_script child_query_values;
	struct pkm_lcs_kunit_drop_key_source_script drop_key;
	struct pkm_lcs_kunit_query_values_source_script query_values;
	struct pkm_lcs_kunit_delete_value_source_script delete_value;
	struct pkm_lcs_kunit_blanket_tombstone_source_script blanket_tombstone;
	struct pkm_lcs_kunit_path_entry_source_script replay_root_hidden_path;
	struct pkm_lcs_kunit_set_value_source_script replay_root_value;
	struct pkm_lcs_kunit_blanket_tombstone_source_script replay_root_blanket;
	struct pkm_lcs_kunit_create_source_script replay_non_root_create;
	struct pkm_lcs_kunit_path_entry_source_script replay_non_root_hidden_path;
	struct pkm_lcs_kunit_set_value_source_script replay_non_root_value;
	struct pkm_lcs_kunit_blanket_tombstone_source_script replay_non_root_blanket;
	const u8 *expected_root_write_sd;
	size_t expected_root_write_sd_len;
	u64 expected_root_last_write_time;
	u64 expected_non_root_last_write_time;
	u32 begin_status;
	u32 commit_status;
	u32 abort_status;
	u64 transaction_id;
	u64 commit_request_id;
	u32 reads;
	u32 writes;
	bool saw_commit;
	bool saw_abort;
	bool commit_request_id_present;
	bool commit_no_response;
	bool expect_commit;
	bool expect_read_key;
	bool expect_root_content_probe;
	bool expect_root_path_delete;
	bool expect_child_teardown;
	bool expect_child_path_delete;
	bool expect_grandchild_teardown;
	bool expect_child_teardown_abort_after_enum;
	bool expect_root_value_delete;
	bool expect_root_blanket_delete;
	bool expect_root_write_key;
	bool expect_replay_root_hidden_path;
	bool expect_replay_root_value;
	bool expect_replay_root_blanket;
	bool expect_replay_non_root_key;
	bool expect_replay_non_root_path;
	bool expect_replay_non_root_hidden_path;
	bool expect_replay_non_root_value;
	bool expect_replay_non_root_blanket;
	int result;
};


struct pkm_lcs_kunit_guid_sequence {
	const u8 (*guids)[16];
	u32 count;
	u32 calls;
};


struct pkm_lcs_kunit_walk_then_read_create_source_script {
	struct file *file;
	struct pkm_lcs_kunit_walk_source_script walk;
	struct pkm_lcs_kunit_walk_source_script parent_walk;
	struct pkm_lcs_kunit_read_then_create_source_script create;
	u32 reads;
	u32 writes;
	bool wait_for_stop_after_completion;
	int result;
};


struct pkm_lcs_kunit_blocking_source_read_script {
	struct file *file;
	u8 *buf;
	size_t buf_len;
	ssize_t ret;
	struct completion started;
	struct completion done;
};


struct pkm_lcs_kunit_txn_create_flow_source_script {
	struct file *file;
	struct pkm_lcs_kunit_walk_source_script walk;
	struct pkm_lcs_kunit_read_key_source_script read_key;
	struct pkm_lcs_kunit_transaction_source_script begin;
	struct pkm_lcs_kunit_create_source_script create;
	struct pkm_lcs_kunit_walk_source_script retry_walk;
	bool expect_begin;
	bool expect_create;
	bool expect_retry_walk;
	u32 reads;
	u32 writes;
	int result;
};


#define PKM_LCS_KUNIT_RUNTIME_RESPONSE_SIZE 1024U


struct pkm_lcs_kunit_poll_capture {
	poll_table table;
	struct file *file;
	wait_queue_head_t *wait_address;
	unsigned int calls;
};


struct pkm_lcs_kunit_slot_wait_round_trip_script {
	struct pkm_lcs_source_response_result response;
	struct pkm_lcs_source_enqueue_result enqueue;
	struct completion started;
	struct completion done;
	long ret;
};


/* Helper prototypes (definitions in kunit_common.c). */

bool pkm_lcs_kunit_usercopy_read(void *raw_ctx, void *dst,
					const void __user *src, size_t len);

bool pkm_lcs_kunit_usercopy_write(void *raw_ctx, void __user *dst,
					 const void *src, size_t len);

size_t pkm_lcs_kunit_usercopy_strnlen(void *raw_ctx,
					     const char __user *src,
					     size_t max);

struct pkm_lcs_usercopy_ops pkm_lcs_kunit_usercopy_ops(
	struct pkm_lcs_kunit_usercopy_ctx *ctx);

ssize_t pkm_lcs_kunit_backup_output_write_iter(
	struct kiocb *iocb, struct iov_iter *from);

ssize_t pkm_lcs_kunit_restore_input_read_iter(
	struct kiocb *iocb, struct iov_iter *to);

void pkm_lcs_kunit_build_register_args(
	struct reg_src_register_args *args, struct reg_src_hive_entry *hive,
	const char *name, u8 root_guid_first, u64 max_sequence);

void pkm_lcs_kunit_build_private_register_args(
	struct reg_src_register_args *args, struct reg_src_hive_entry *hive,
	const char *name, u8 root_guid_first, u8 scope_guid_first);

void pkm_lcs_kunit_expect_materialized_component(
	struct kunit *test, const struct pkm_lcs_materialized_path *path,
	u32 index, const char *expected);

long pkm_lcs_kunit_publish_create_finish_fd(void);

long pkm_lcs_kunit_retry_open_resolution_prepare(
	struct pkm_lcs_create_missing_parent_resolution *resolution,
	const u8 root_guid[RSI_GUID_SIZE], const char *child_name);

bool pkm_lcs_kunit_buffer_contains(const u8 *buffer, size_t buffer_len,
					  const char *needle);

void pkm_lcs_kunit_expect_latest_lcs_event(
	struct kunit *test, const char *event_type, const char *payload_field);

void pkm_lcs_kunit_expect_latest_kmes_origin_event(
	struct kunit *test, const char *event_type, u8 expected_map_prefix,
	const char *first_payload_field, const char *second_payload_field);

void pkm_lcs_kunit_expect_runtime_limits_defaults(
	struct kunit *test, const struct pkm_lcs_runtime_limits *limits);

void pkm_lcs_kunit_fill_self_config_defaults(
	struct pkm_lcs_self_config_entry *entries);

bool pkm_lcs_kunit_buffer_contains_bytes(const u8 *buffer,
						size_t buffer_len,
						const u8 *needle,
						size_t needle_len);

long pkm_lcs_kunit_publish_key_fd_with_access(u32 granted_access);

void pkm_lcs_kunit_flush_deferred_key_fd_release(void);

long pkm_lcs_kunit_publish_key_fd_for_source(
	u32 source_id, const u8 root_guid[PKM_LCS_GUID_BYTES],
	const u8 key_guid[PKM_LCS_GUID_BYTES], u32 granted_access);

long pkm_lcs_kunit_publish_key_fd_from_path(
	u32 source_id, u32 granted_access, const char * const *path,
	const u8 (*ancestors)[PKM_LCS_GUID_BYTES], u32 depth);

long pkm_lcs_kunit_publish_key_fd_with_depth(u32 depth);

void pkm_lcs_kunit_expect_set_value_success(
	struct kunit *test, struct file *file, int fd, const void *token,
	const struct pkm_lcs_usercopy_ops *ops,
	const struct reg_set_value_args *args,
	const u8 guid[RSI_GUID_SIZE], const char *value_name,
	const u8 *data, size_t data_len, u32 value_type);

void pkm_lcs_kunit_expect_set_value_layer_refresh_success(
	struct kunit *test, struct file *file, int fd, const void *token,
	const struct pkm_lcs_usercopy_ops *ops,
	const struct reg_set_value_args *args,
	const u8 guid[RSI_GUID_SIZE], const char *value_name,
	const u8 *data, size_t data_len, u32 value_type,
	const char *layer_name, const u8 *metadata_sd, size_t metadata_sd_len,
	u32 refresh_precedence, u32 refresh_enabled);

int pkm_lcs_kunit_external_fd(unsigned int flags);

int pkm_lcs_kunit_backup_output_fd(
	struct pkm_lcs_kunit_backup_output_file *output);

int pkm_lcs_kunit_restore_input_fd(
	struct pkm_lcs_kunit_restore_input_file *input);

int pkm_lcs_kunit_restore_stream_append(
	struct pkm_lcs_kunit_restore_input_file *input,
	const void *src, size_t len);

int pkm_lcs_kunit_restore_stream_append_u16(
	struct pkm_lcs_kunit_restore_input_file *input, u16 value);

int pkm_lcs_kunit_restore_stream_append_u32(
	struct pkm_lcs_kunit_restore_input_file *input, u32 value);

int pkm_lcs_kunit_restore_stream_append_u64(
	struct pkm_lcs_kunit_restore_input_file *input, u64 value);

int pkm_lcs_kunit_restore_stream_append_s64(
	struct pkm_lcs_kunit_restore_input_file *input, s64 value);

int pkm_lcs_kunit_restore_stream_append_record_header(
	struct pkm_lcs_kunit_restore_input_file *input,
	u16 record_type, u32 record_len);

int pkm_lcs_kunit_restore_stream_append_key_record(
	struct pkm_lcs_kunit_restore_input_file *input,
	const u8 guid[PKM_LCS_GUID_BYTES], bool volatile_key, bool symlink);

int pkm_lcs_kunit_restore_stream_append_header(
	struct pkm_lcs_kunit_restore_input_file *input);

int pkm_lcs_kunit_restore_stream_append_trailer(
	struct pkm_lcs_kunit_restore_input_file *input, u64 record_count);

int pkm_lcs_kunit_restore_stream_append_layer_record(
	struct pkm_lcs_kunit_restore_input_file *input,
	const struct pkm_lcs_kunit_restore_layer_record *layer);

int pkm_lcs_kunit_restore_stream_append_data_record(
	struct pkm_lcs_kunit_restore_input_file *input,
	const struct pkm_lcs_kunit_restore_data_record *record, u64 sequence);

int pkm_lcs_kunit_restore_stream_build_valid(
	struct pkm_lcs_kunit_restore_input_file *input, bool include_unknown);

int pkm_lcs_kunit_restore_stream_build_with_root_keys(
	struct pkm_lcs_kunit_restore_input_file *input, bool include_unknown,
	u32 root_key_count, bool root_volatile, bool root_symlink);

int pkm_lcs_kunit_restore_stream_build_with_layers(
	struct pkm_lcs_kunit_restore_input_file *input,
	const struct pkm_lcs_kunit_restore_layer_record *layers,
	u32 layer_count, bool layer_after_key);

int pkm_lcs_kunit_restore_stream_build_with_data_records(
	struct pkm_lcs_kunit_restore_input_file *input,
	const struct pkm_lcs_kunit_restore_layer_record *layers,
	u32 layer_count,
	const struct pkm_lcs_kunit_restore_data_record *records,
	u32 record_count);

long pkm_lcs_kunit_publish_source_one_key_fd_with_access(
	u32 granted_access);

long pkm_lcs_kunit_publish_source_one_backup_key_fd(void);

long pkm_lcs_kunit_publish_restarted_missing_key_fd(
	struct file *resumed_file, const void **source_token_out,
	u32 granted_access);

long pkm_lcs_kunit_publish_restarted_missing_backup_restore_fd(
	struct file *resumed_file, const void **source_token_out);

ssize_t pkm_lcs_kunit_backup_snapshot_read_source_request(
	struct pkm_lcs_kunit_backup_snapshot_source_script *script,
	u8 *request, size_t request_len);

int pkm_lcs_kunit_backup_snapshot_write_status(
	struct pkm_lcs_kunit_backup_snapshot_source_script *script,
	u64 request_id, u16 op_code, u32 status);

int pkm_lcs_kunit_backup_snapshot_write_empty_enum_children(
	struct pkm_lcs_kunit_backup_snapshot_source_script *script,
	u64 request_id);

int pkm_lcs_kunit_backup_snapshot_write_empty_query_values(
	struct pkm_lcs_kunit_backup_snapshot_source_script *script,
	u64 request_id);

int pkm_lcs_kunit_backup_snapshot_write_query_values(
	struct pkm_lcs_kunit_backup_snapshot_source_script *script,
	u64 request_id, const char *value_name, const u8 *value_data,
	size_t value_data_len, bool include_blanket);

int pkm_lcs_kunit_backup_snapshot_write_root_query_values(
	struct pkm_lcs_kunit_backup_snapshot_source_script *script,
	u64 request_id);

int pkm_lcs_kunit_backup_snapshot_write_child_query_values(
	struct pkm_lcs_kunit_backup_snapshot_source_script *script,
	u64 request_id);

int pkm_lcs_kunit_backup_snapshot_write_grandchild_query_values(
	struct pkm_lcs_kunit_backup_snapshot_source_script *script,
	u64 request_id);

int pkm_lcs_kunit_backup_snapshot_handle_export_read(
	struct pkm_lcs_kunit_backup_snapshot_source_script *script,
	u16 expected_op, const u8 expected_guid[PKM_LCS_GUID_BYTES],
	u8 *request, size_t request_len);

void pkm_lcs_kunit_expect_backup_stream_record_types(
	struct kunit *test,
	const struct pkm_lcs_kunit_backup_output_file *output,
	const u16 *expected_types, size_t expected_type_count,
	const u8 expected_root_guid[PKM_LCS_GUID_BYTES]);

int pkm_lcs_kunit_backup_stream_record_at(
	const struct pkm_lcs_kunit_backup_output_file *output,
	size_t record_index, u16 expected_type, const u8 **frame_out,
	size_t *frame_len_out);

void pkm_lcs_kunit_expect_empty_backup_stream(
	struct kunit *test,
	const struct pkm_lcs_kunit_backup_output_file *output,
	const u8 expected_root_guid[PKM_LCS_GUID_BYTES]);

void pkm_lcs_kunit_expect_layer_manifest_record(
	struct kunit *test, const u8 *frame, size_t frame_len,
	const char *expected_name, u32 expected_precedence, u8 expected_enabled,
	const u8 *expected_owner, size_t expected_owner_len);

void pkm_lcs_kunit_expect_key_record(
	struct kunit *test, const u8 *frame, size_t frame_len,
	const u8 expected_guid[PKM_LCS_GUID_BYTES], u32 expected_flags,
	const u8 *expected_sd, size_t expected_sd_len, s64 expected_last_write);

void pkm_lcs_kunit_expect_path_entry_record(
	struct kunit *test, const u8 *frame, size_t frame_len,
	const u8 expected_parent[PKM_LCS_GUID_BYTES],
	const char *expected_child_name,
	const u8 expected_child[PKM_LCS_GUID_BYTES],
	const char *expected_layer, u64 expected_sequence);

void pkm_lcs_kunit_expect_value_record(
	struct kunit *test, const u8 *frame, size_t frame_len,
	const u8 expected_key[PKM_LCS_GUID_BYTES], const char *expected_name,
	u32 expected_type, const u8 *expected_data, size_t expected_data_len,
	const char *expected_layer, u64 expected_sequence);

void pkm_lcs_kunit_expect_blanket_tombstone_record(
	struct kunit *test, const u8 *frame, size_t frame_len,
	const u8 expected_key[PKM_LCS_GUID_BYTES], const char *expected_layer,
	u64 expected_sequence);

int pkm_lcs_kunit_backup_snapshot_source_thread(void *raw_script);

int pkm_lcs_kunit_backup_call_thread(void *raw_script);

int pkm_lcs_kunit_restore_txn_source_read_request(
	struct pkm_lcs_kunit_restore_txn_source_script *script, u8 *request,
	size_t request_len, ssize_t *count_out);

int pkm_lcs_kunit_restore_txn_source_write_status(
	struct pkm_lcs_kunit_restore_txn_source_script *script,
	u64 request_id, u16 request_op, u32 status);

int pkm_lcs_kunit_restore_txn_expect_non_root_create_key(
	struct pkm_lcs_kunit_restore_txn_source_script *script);

int pkm_lcs_kunit_restore_txn_expect_non_root_write_key(
	struct pkm_lcs_kunit_restore_txn_source_script *script);

int pkm_lcs_kunit_restore_txn_expect_non_root_create_entry(
	struct pkm_lcs_kunit_restore_txn_source_script *script);

int pkm_lcs_kunit_restore_txn_source_thread(void *raw_script);

void pkm_lcs_kunit_key_fd_restore_commit_timeout_late_response(
	struct kunit *test, u32 late_status, bool expect_effects);

void pkm_lcs_kunit_expect_restore_stream_result(
	struct kunit *test, struct pkm_lcs_kunit_restore_input_file *input,
	long expected_ret);

void
pkm_lcs_kunit_expect_restore_root_flag_result_with_sequence(
	struct kunit *test, struct pkm_lcs_kunit_restore_input_file *input,
	long expected_ret, bool target_volatile, bool target_symlink,
	bool override_sequence, u64 next_sequence_override,
	bool expect_root_hidden_replay, u64 *sequence_after_out);

void
pkm_lcs_kunit_expect_restore_root_flag_result(
	struct kunit *test, struct pkm_lcs_kunit_restore_input_file *input,
	long expected_ret, bool target_volatile, bool target_symlink);

long pkm_lcs_kunit_restore_precedence_publish_layers_root(
	struct kunit *test, const char * const *path,
	u8 ancestors[4][PKM_LCS_GUID_BYTES]);

u32 pkm_lcs_kunit_write_direct_watch_event(u8 *dst, size_t dst_len,
						  u32 event_type,
						  const char *name);

void pkm_lcs_kunit_expect_drop_key_request(
	struct kunit *test, struct file *file,
	const u8 guid[PKM_LCS_GUID_BYTES]);

void pkm_lcs_kunit_create_missing_parent_resolution_set_sd(
	struct kunit *test, struct pkm_lcs_create_missing_parent_resolution *result,
	const u8 *sd, size_t sd_len);

void pkm_lcs_kunit_guid_sequence_generate(void *raw_ctx, u8 guid[16]);

struct pkm_lcs_key_guid_generator
pkm_lcs_kunit_guid_generator(struct pkm_lcs_kunit_guid_sequence *sequence);

void pkm_lcs_kunit_setup_registered_source(struct kunit *test,
						  struct file *file,
						  const void **token_out);

struct task_struct *pkm_lcs_kunit_kthread_run(int (*threadfn)(void *),
						     void *data,
						     const char *name);

int pkm_lcs_kunit_kthread_stop(struct task_struct *task);

void pkm_lcs_kunit_build_lookup_frame(struct kunit *test, u8 *frame,
					     size_t frame_len, u64 request_id,
					     const char *child_name,
					     size_t *built_len);

void pkm_lcs_kunit_build_status_response(struct kunit *test, u8 *frame,
						size_t frame_len,
						u64 request_id, u16 request_op,
						u32 status, size_t *built_len);

int pkm_lcs_kunit_create_source_read_request(
	struct pkm_lcs_kunit_create_source_script *script, u8 *request,
	size_t request_len, ssize_t *count);

int pkm_lcs_kunit_create_source_expect_bytes(
	const u8 *request, size_t request_len, size_t *offset,
	const void *expected, size_t expected_len);

int pkm_lcs_kunit_create_source_expect_string(
	const u8 *request, size_t request_len, size_t *offset,
	const char *expected);

int pkm_lcs_kunit_flush_source_thread(void *data);

int pkm_lcs_kunit_drop_key_source_thread(void *data);

int pkm_lcs_kunit_delete_layer_source_thread(void *data);

int pkm_lcs_kunit_path_entry_source_thread(void *data);

int pkm_lcs_kunit_hide_key_ioctl_source_thread(void *raw_script);

int pkm_lcs_kunit_create_source_expect_entry_request(
	struct pkm_lcs_kunit_create_source_script *script, const u8 *request,
	size_t request_len, u64 *request_id);

int pkm_lcs_kunit_create_source_expect_key_request(
	struct pkm_lcs_kunit_create_source_script *script, const u8 *request,
	size_t request_len, u64 *request_id);

int pkm_lcs_kunit_create_source_write_status(
	struct pkm_lcs_kunit_create_source_script *script, u64 request_id,
	u16 request_op, u32 status);

int pkm_lcs_kunit_create_source_thread(void *raw_script);

void pkm_lcs_kunit_rsi_append_bytes(struct kunit *test, u8 *frame,
					   size_t frame_len, size_t *offset,
					   const void *bytes, size_t len);

void pkm_lcs_kunit_rsi_append_u8(struct kunit *test, u8 *frame,
					size_t frame_len, size_t *offset,
					u8 value);

void pkm_lcs_kunit_rsi_append_u32(struct kunit *test, u8 *frame,
					 size_t frame_len, size_t *offset,
					 u32 value);

void pkm_lcs_kunit_rsi_append_u64(struct kunit *test, u8 *frame,
					 size_t frame_len, size_t *offset,
					 u64 value);

void pkm_lcs_kunit_rsi_append_len_prefixed(
	struct kunit *test, u8 *frame, size_t frame_len, size_t *offset,
	const void *bytes, size_t len);

void pkm_lcs_kunit_rsi_response_begin(struct kunit *test, u8 *frame,
					     size_t frame_len, u64 request_id,
					     u16 response_op, u32 status,
					     size_t *offset);

void pkm_lcs_kunit_rsi_finish_response(struct kunit *test, u8 *frame,
					      size_t offset,
					      size_t *built_len);

void pkm_lcs_kunit_rsi_append_lookup_path_entry(
	struct kunit *test, u8 *frame, size_t frame_len, size_t *offset,
	const char *layer_name, u8 target_type, const u8 guid[RSI_GUID_SIZE],
	u64 sequence);

void pkm_lcs_kunit_rsi_append_lookup_metadata(
	struct kunit *test, u8 *frame, size_t frame_len, size_t *offset,
	const u8 guid[RSI_GUID_SIZE], const u8 *sd, size_t sd_len);

void pkm_lcs_kunit_rsi_append_lookup_metadata_ex(
	struct kunit *test, u8 *frame, size_t frame_len, size_t *offset,
	const u8 guid[RSI_GUID_SIZE], const u8 *sd, size_t sd_len,
	u8 volatile_key, u8 symlink, u64 last_write_time);

void pkm_lcs_kunit_rsi_append_query_value_entry(
	struct kunit *test, u8 *frame, size_t frame_len, size_t *offset,
	const char *value_name, const char *layer_name, u32 value_type,
	const u8 *data, size_t data_len, u64 sequence);

void pkm_lcs_kunit_rsi_append_query_blanket(
	struct kunit *test, u8 *frame, size_t frame_len, size_t *offset,
	const char *layer_name, u64 sequence);

int pkm_lcs_kunit_walk_source_append(void *dst, size_t dst_len,
					    size_t *offset, const void *src,
					    size_t src_len);

int pkm_lcs_kunit_walk_source_append_u8(u8 *dst, size_t dst_len,
					       size_t *offset, u8 value);

int pkm_lcs_kunit_walk_source_append_u32(u8 *dst, size_t dst_len,
						size_t *offset, u32 value);

int pkm_lcs_kunit_walk_source_append_u64(u8 *dst, size_t dst_len,
						size_t *offset, u64 value);

int pkm_lcs_kunit_walk_source_append_len_prefixed(
	u8 *dst, size_t dst_len, size_t *offset, const void *src,
	size_t src_len);

int pkm_lcs_kunit_walk_source_build_response(
	const struct pkm_lcs_kunit_walk_source_step *step, u64 request_id,
	u16 request_op, u32 index, u8 *response, size_t response_len,
	size_t *built_len);

int pkm_lcs_kunit_walk_source_thread(void *raw_script);

int pkm_lcs_kunit_read_key_source_build_response(
	const struct pkm_lcs_kunit_read_key_source_script *script,
	u64 request_id, u8 *response, size_t response_len, size_t *built_len);

int pkm_lcs_kunit_read_key_source_thread(void *raw_script);

int pkm_lcs_kunit_set_security_source_thread(void *raw_script);

int pkm_lcs_kunit_read_then_create_source_thread(void *raw_script);

int pkm_lcs_kunit_walk_then_read_source_thread(void *raw_script);

int
pkm_lcs_kunit_walk_then_query_values_source_thread(void *raw_script);

int pkm_lcs_kunit_walk_then_read_create_source_thread(void *raw_script);

int pkm_lcs_kunit_query_values_source_append_value(
	u8 *response, size_t response_len, size_t *offset, const char *value_name,
	const char *layer_name, u32 value_type, const u8 *data, size_t data_len,
	u64 sequence);

int pkm_lcs_kunit_query_values_source_build_response(
	const struct pkm_lcs_kunit_query_values_source_script *script,
	u64 request_id, u8 *response, size_t response_len, size_t *built_len);

int pkm_lcs_kunit_query_values_source_thread(void *raw_script);

int pkm_lcs_kunit_layer_metadata_refresh_source_read(
	struct pkm_lcs_kunit_layer_metadata_refresh_source_script *script,
	u8 *request, size_t request_len, ssize_t *count_out);

int pkm_lcs_kunit_layer_metadata_refresh_write_frame(
	struct pkm_lcs_kunit_layer_metadata_refresh_source_script *script,
	const u8 *response, size_t response_len);

int pkm_lcs_kunit_layer_metadata_refresh_handle_read_key(
	struct pkm_lcs_kunit_layer_metadata_refresh_source_script *script,
	u8 *request, size_t request_len);

int pkm_lcs_kunit_layer_metadata_refresh_write_query_response(
	struct pkm_lcs_kunit_layer_metadata_refresh_source_script *script,
	u64 request_id, const char *value_name, bool present, u32 value);

int pkm_lcs_kunit_layer_metadata_refresh_write_binary_query_response(
	struct pkm_lcs_kunit_layer_metadata_refresh_source_script *script,
	u64 request_id, const char *value_name, bool present, const u8 *data,
	size_t data_len);

int pkm_lcs_kunit_layer_metadata_refresh_handle_query(
	struct pkm_lcs_kunit_layer_metadata_refresh_source_script *script,
	u8 *request, size_t request_len, const char *expected_value_name,
	bool present, u32 value);

int pkm_lcs_kunit_layer_metadata_refresh_handle_owner_query(
	struct pkm_lcs_kunit_layer_metadata_refresh_source_script *script,
	u8 *request, size_t request_len);

bool pkm_lcs_kunit_layer_metadata_refresh_stops_after_enabled(
	const struct pkm_lcs_kunit_layer_metadata_refresh_source_script *script);

int pkm_lcs_kunit_layer_metadata_refresh_source_thread(void *raw_script);

int pkm_lcs_kunit_layer_create_watch_source_thread(void *raw_script);

int pkm_lcs_kunit_set_security_layer_refresh_source_thread(
	void *raw_script);

int pkm_lcs_kunit_create_layer_refresh_source_thread(void *raw_script);

int pkm_lcs_kunit_set_value_source_thread(void *raw_script);

int pkm_lcs_kunit_delete_value_source_thread(void *raw_script);

int pkm_lcs_kunit_blanket_tombstone_source_thread(void *raw_script);

ssize_t pkm_lcs_kunit_set_value_ioctl_source_read(
	struct pkm_lcs_kunit_set_value_ioctl_source_script *script,
	u8 *request, size_t request_len);

int pkm_lcs_kunit_set_value_ioctl_source_write_status(
	struct pkm_lcs_kunit_set_value_ioctl_source_script *script,
	u64 request_id, u16 request_op, u32 status);

int pkm_lcs_kunit_set_value_ioctl_source_write_empty_values(
	struct pkm_lcs_kunit_set_value_ioctl_source_script *script,
	u64 request_id);

int pkm_lcs_kunit_set_value_ioctl_source_handle_query(
	struct pkm_lcs_kunit_set_value_ioctl_source_script *script,
	u8 *request, size_t request_len);

int pkm_lcs_kunit_set_value_ioctl_source_handle_set_value(
	struct pkm_lcs_kunit_set_value_ioctl_source_script *script,
	u8 *request, size_t request_len, bool *continue_after_set);

int pkm_lcs_kunit_set_value_ioctl_source_handle_write_key(
	struct pkm_lcs_kunit_set_value_ioctl_source_script *script,
	u8 *request, size_t request_len);

int pkm_lcs_kunit_set_value_ioctl_source_handle_layer_refresh(
	struct pkm_lcs_kunit_set_value_ioctl_source_script *script,
	u8 *request, size_t request_len);

int pkm_lcs_kunit_set_value_ioctl_source_thread(void *raw_script);

ssize_t pkm_lcs_kunit_delete_value_ioctl_source_read(
	struct pkm_lcs_kunit_delete_value_ioctl_source_script *script,
	u8 *request, size_t request_len);

int pkm_lcs_kunit_delete_value_ioctl_source_write_status(
	struct pkm_lcs_kunit_delete_value_ioctl_source_script *script,
	u64 request_id, u16 request_op, u32 status);

int pkm_lcs_kunit_delete_value_ioctl_source_write_query_response(
	struct pkm_lcs_kunit_delete_value_ioctl_source_script *script,
	u64 request_id, bool after);

int pkm_lcs_kunit_delete_value_ioctl_source_handle_query(
	struct pkm_lcs_kunit_delete_value_ioctl_source_script *script,
	u8 *request, size_t request_len, bool after);

int pkm_lcs_kunit_delete_value_ioctl_source_handle_delete(
	struct pkm_lcs_kunit_delete_value_ioctl_source_script *script,
	u8 *request, size_t request_len, bool *continue_after_delete);

int pkm_lcs_kunit_delete_value_ioctl_source_handle_write_key(
	struct pkm_lcs_kunit_delete_value_ioctl_source_script *script,
	u8 *request, size_t request_len);

int pkm_lcs_kunit_delete_value_ioctl_source_thread(void *raw_script);

ssize_t pkm_lcs_kunit_blanket_tombstone_ioctl_source_read(
	struct pkm_lcs_kunit_blanket_tombstone_ioctl_source_script *script,
	u8 *request, size_t request_len);

int pkm_lcs_kunit_blanket_tombstone_ioctl_source_write_status(
	struct pkm_lcs_kunit_blanket_tombstone_ioctl_source_script *script,
	u64 request_id, u16 request_op, u32 status);

int
pkm_lcs_kunit_blanket_tombstone_ioctl_source_write_query_response(
	struct pkm_lcs_kunit_blanket_tombstone_ioctl_source_script *script,
	u64 request_id, bool after);

int pkm_lcs_kunit_blanket_tombstone_ioctl_source_handle_query(
	struct pkm_lcs_kunit_blanket_tombstone_ioctl_source_script *script,
	u8 *request, size_t request_len, bool after);

int pkm_lcs_kunit_blanket_tombstone_ioctl_source_handle_blanket(
	struct pkm_lcs_kunit_blanket_tombstone_ioctl_source_script *script,
	u8 *request, size_t request_len, bool *continue_after_blanket);

int pkm_lcs_kunit_blanket_tombstone_ioctl_source_handle_write_key(
	struct pkm_lcs_kunit_blanket_tombstone_ioctl_source_script *script,
	u8 *request, size_t request_len);

int
pkm_lcs_kunit_blanket_tombstone_ioctl_source_thread(void *raw_script);

int pkm_lcs_kunit_enum_children_source_build_response(
	const struct pkm_lcs_kunit_enum_children_source_script *script,
	u64 request_id, u8 *response, size_t response_len, size_t *built_len);

int pkm_lcs_kunit_enum_children_source_thread(void *raw_script);

int pkm_lcs_kunit_layer_metadata_refresh_all_source_thread(
	void *raw_script);

int pkm_lcs_kunit_source_bootstrap_handle_layer_refresh_all(
	struct pkm_lcs_kunit_source_bootstrap_source_script *script);

int pkm_lcs_kunit_source_bootstrap_source_thread(void *raw_script);

ssize_t pkm_lcs_kunit_delete_key_ioctl_source_read(
	struct pkm_lcs_kunit_delete_key_ioctl_source_script *script,
	u8 *request, size_t request_len);

int pkm_lcs_kunit_delete_key_ioctl_source_write_status(
	struct pkm_lcs_kunit_delete_key_ioctl_source_script *script,
	u64 request_id, u16 request_op, u32 status);

int pkm_lcs_kunit_delete_key_ioctl_source_write_empty_enum(
	struct pkm_lcs_kunit_delete_key_ioctl_source_script *script,
	u64 request_id);

int pkm_lcs_kunit_delete_key_ioctl_source_handle_enum(
	struct pkm_lcs_kunit_delete_key_ioctl_source_script *script,
	u8 *request, size_t request_len, bool *has_visible_children);

int pkm_lcs_kunit_delete_key_ioctl_source_handle_delete(
	struct pkm_lcs_kunit_delete_key_ioctl_source_script *script,
	u8 *request, size_t request_len, bool *continue_after_delete);

int pkm_lcs_kunit_delete_key_ioctl_source_handle_lookup(
	struct pkm_lcs_kunit_delete_key_ioctl_source_script *script,
	u8 *request, size_t request_len);

int pkm_lcs_kunit_delete_key_ioctl_source_handle_parent_write(
	struct pkm_lcs_kunit_delete_key_ioctl_source_script *script,
	u8 *request, size_t request_len);

int pkm_lcs_kunit_delete_key_ioctl_source_thread(void *raw_script);

ssize_t pkm_lcs_kunit_symlink_follow_read_request(
	struct pkm_lcs_kunit_symlink_follow_source_script *script,
	u8 *request, size_t request_len);

int pkm_lcs_kunit_symlink_follow_write_response(
	struct pkm_lcs_kunit_symlink_follow_source_script *script,
	const u8 *response, size_t response_len);

int pkm_lcs_kunit_symlink_follow_handle_lookup(
	struct pkm_lcs_kunit_symlink_follow_source_script *script,
	const struct pkm_lcs_kunit_walk_source_step *step, u8 *request,
	size_t request_len, u8 *response, size_t response_len);

int pkm_lcs_kunit_symlink_follow_handle_query(
	struct pkm_lcs_kunit_symlink_follow_source_script *script,
	u8 *request, size_t request_len, u8 *response, size_t response_len);

int pkm_lcs_kunit_symlink_follow_source_thread(void *raw_script);

ssize_t pkm_lcs_kunit_symlink_sequence_read_request(
	struct pkm_lcs_kunit_symlink_sequence_source_script *script,
	u8 *request, size_t request_len);

int pkm_lcs_kunit_symlink_sequence_write_response(
	struct pkm_lcs_kunit_symlink_sequence_source_script *script,
	const u8 *response, size_t response_len);

int pkm_lcs_kunit_symlink_sequence_handle_lookup(
	struct pkm_lcs_kunit_symlink_sequence_source_script *script,
	const struct pkm_lcs_kunit_symlink_sequence_op *op, u8 *request,
	size_t request_len, u8 *response, size_t response_len, u32 index);

int pkm_lcs_kunit_symlink_sequence_handle_query(
	struct pkm_lcs_kunit_symlink_sequence_source_script *script,
	const struct pkm_lcs_kunit_symlink_sequence_op *op, u8 *request,
	size_t request_len, u8 *response, size_t response_len);

int pkm_lcs_kunit_symlink_sequence_handle_read_key(
	struct pkm_lcs_kunit_symlink_sequence_source_script *script,
	const struct pkm_lcs_kunit_symlink_sequence_op *op, u8 *request,
	size_t request_len, u8 *response, size_t response_len);

int pkm_lcs_kunit_symlink_sequence_handle_enum_children(
	struct pkm_lcs_kunit_symlink_sequence_source_script *script,
	const struct pkm_lcs_kunit_symlink_sequence_op *op, u8 *request,
	size_t request_len, u8 *response, size_t response_len);

int pkm_lcs_kunit_symlink_sequence_source_thread(void *raw_script);

int pkm_lcs_kunit_blocking_source_read_thread(void *raw_script);

void pkm_lcs_kunit_source_fd_force_closing(
	struct pkm_lcs_source_fd *source_fd);

int pkm_lcs_kunit_transaction_source_thread(void *data);

int pkm_lcs_kunit_txn_create_flow_source_thread(void *raw_script);

void pkm_lcs_kunit_run_transaction_source_round_trip(
	struct kunit *test,
	struct pkm_lcs_kunit_transaction_source_script *script,
	long (*round_trip)(u32 source_id, u64 transaction_id,
			   struct pkm_lcs_source_response_result *response,
			   struct pkm_lcs_source_enqueue_result *enqueue),
	u64 transaction_id, long expected_ret,
	struct pkm_lcs_source_response_result *response,
	struct pkm_lcs_source_enqueue_result *enqueue);

long pkm_lcs_kunit_commit_round_trip_default(
	u32 source_id, u64 transaction_id,
	struct pkm_lcs_source_response_result *response,
	struct pkm_lcs_source_enqueue_result *enqueue);

long pkm_lcs_kunit_begin_readwrite_round_trip_default(
	u32 source_id, u64 transaction_id,
	struct pkm_lcs_source_response_result *response,
	struct pkm_lcs_source_enqueue_result *enqueue);

long pkm_lcs_kunit_abort_round_trip_default(
	u32 source_id, u64 transaction_id,
	struct pkm_lcs_source_response_result *response,
	struct pkm_lcs_source_enqueue_result *enqueue);

void pkm_lcs_kunit_append_one_create_log(struct kunit *test, int fd,
						const u8 root_guid[16],
						u64 sequence);

void pkm_lcs_kunit_append_set_value_log_for_layer(
	struct kunit *test, int fd, const u8 root_guid[16],
	const char *layer, u64 sequence);

void pkm_lcs_kunit_commit_timeout_late_response(
	struct kunit *test, u32 status);

void pkm_lcs_kunit_commit_timeout_late_create_watch(
	struct kunit *test, u32 status, bool expect_event);

void pkm_lcs_kunit_commit_timeout_closed_fd_late_response(
	struct kunit *test, u32 status);

void pkm_lcs_kunit_create_missing_set_child_path(
	struct kunit *test, struct pkm_lcs_create_missing_parent_resolution *res);

void pkm_lcs_kunit_create_missing_set_layer_metadata_child_path(
	struct kunit *test, struct pkm_lcs_create_missing_parent_resolution *res);

long pkm_lcs_kunit_dispatch_status_only_waitable_request(
	u16 op_code, struct pkm_lcs_source_response_waiter *waiter,
	struct pkm_lcs_source_enqueue_result *enqueue);

void pkm_lcs_kunit_fill_name(char *name, size_t len, char value);

void pkm_lcs_kunit_expect_source_validation_audit(
	struct kunit *test, const char *validation_class,
	const u8 key_guid[RSI_GUID_SIZE]);

void pkm_lcs_kunit_poll_capture_queue(
	struct file *file, wait_queue_head_t *wait_address,
	struct poll_table_struct *table);

int pkm_lcs_kunit_slot_wait_round_trip_thread(void *raw_script);

/* Shared const test data (small; duplicated per TU is fine). */

static __maybe_unused const u8 pkm_lcs_kunit_system_sid[] = {
	0x01, 0x01, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x05,
	0x12, 0x00, 0x00, 0x00,
};


static __maybe_unused const u8 pkm_lcs_kunit_everyone_sid[] = {
	0x01, 0x01, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x01,
	0x00, 0x00, 0x00, 0x00,
};


static __maybe_unused const u8 pkm_lcs_kunit_owner_only_sd[] = {
	0x01, 0x00, 0x00, 0x80,
	0x14, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00,
	0x01, 0x01, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x05,
	0x12, 0x00, 0x00, 0x00,
};


static __maybe_unused const u8 pkm_lcs_kunit_kmes_watch_guid[RSI_GUID_SIZE] = { 0x6b };


struct pkm_lcs_kunit_delete_key_ioctl_source_script;

struct pkm_lcs_kunit_delete_layer_source_script;


static __maybe_unused const struct file_operations pkm_lcs_kunit_non_key_fops = { };


static __maybe_unused const struct file_operations pkm_lcs_kunit_backup_output_fops = {
	.write_iter = pkm_lcs_kunit_backup_output_write_iter,
};


static __maybe_unused const struct file_operations pkm_lcs_kunit_restore_input_fops = {
	.read_iter = pkm_lcs_kunit_restore_input_read_iter,
};


static __maybe_unused const struct pkm_lcs_kunit_self_config_default
	pkm_lcs_kunit_self_config_defaults[] = {
		{ "RequestTimeoutMs", 30000U },
		{ "TransactionTimeoutMs", 30000U },
		{ "NotificationQueueSize", 256U },
		{ "SymlinkDepthLimit", 16U },
		{ "MaxValueSize", 1048576U },
		{ "MaxKeyDepth", 512U },
		{ "MaxPathComponentLength", 255U },
		{ "MaxTotalPathLength", 16383U },
		{ "MaxLayersPerValue", 128U },
		{ "MaxBoundTransactionsPerSource", 16U },
		{ "MaxReadOnlyTransactionsPerSource", 16U },
		{ "MaxTotalLayers", 1024U },
		{ "MaxRegisteredSources", 32U },
		{ "MaxHivesPerSource", 64U },
		{ "MaxConcurrentRSIRequests", 256U },
		{ "MaxScopeGUIDsPerToken", 8U },
		{ "MaxPrivateLayersPerToken", 16U },
		{ "MaxSubtreeWatchDepth", 0U },
		{ "MaxTransactionWatchEventBurst", 4096U },
	};


static __maybe_unused const u8 pkm_lcs_kunit_restore_header_root_guid[PKM_LCS_GUID_BYTES] = {
	0x61,
};

static __maybe_unused const u8 pkm_lcs_kunit_restore_target_guid[PKM_LCS_GUID_BYTES] = {
	0x52,
};


static __maybe_unused const u8 pkm_lcs_kunit_parent_sd_ci_generic_read[] = {
	/* SECURITY_DESCRIPTOR_RELATIVE */
	0x01, 0x00, 0x04, 0x80, 0x14, 0x00, 0x00, 0x00,
	0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x2c, 0x00, 0x00, 0x00,
	/* Owner: S-1-5-18 */
	0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x05,
	0x12, 0x00, 0x00, 0x00,
	/* Group: S-1-5-18 */
	0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x05,
	0x12, 0x00, 0x00, 0x00,
	/* DACL: one CONTAINER_INHERIT allow ACE for Everyone GENERIC_READ. */
	0x02, 0x00, 0x1c, 0x00, 0x01, 0x00, 0x00, 0x00,
	0x00, 0x02, 0x14, 0x00, 0x00, 0x00, 0x00, 0x80,
	0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
	0x00, 0x00, 0x00, 0x00,
};


static __maybe_unused const u8 pkm_lcs_kunit_parent_sd_create_subkey_ci_generic_read[] = {
	/* SECURITY_DESCRIPTOR_RELATIVE */
	0x01, 0x00, 0x04, 0x80, 0x14, 0x00, 0x00, 0x00,
	0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x2c, 0x00, 0x00, 0x00,
	/* Owner: S-1-5-18 */
	0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x05,
	0x12, 0x00, 0x00, 0x00,
	/* Group: S-1-5-18 */
	0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x05,
	0x12, 0x00, 0x00, 0x00,
	/* DACL: explicit create-subkey plus inheritable generic-read. */
	0x02, 0x00, 0x30, 0x00, 0x02, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x14, 0x00, 0x04, 0x00, 0x00, 0x00,
	0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
	0x00, 0x00, 0x00, 0x00,
	0x00, 0x02, 0x14, 0x00, 0x00, 0x00, 0x00, 0x80,
	0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
	0x00, 0x00, 0x00, 0x00,
};


#endif /* PKM_LCS_KUNIT_COMMON_H */
