#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Generate the ML-DSA-65 KUnit signing vectors for KACS.

KACS signs the 32-byte SHA-256 content hash directly as the message, using
pure ML-DSA (FIPS 204) with an empty context string -- see psd-004 section 6.
The kernel's in-tree ML-DSA is verification-only, so the (public key, message,
signature) triples the KUnit suite verifies against are produced here, out of
tree, with OpenSSL, and checked in as generated source.

The upstream vectors in lib/crypto/tests/mldsa-testvecs.h cannot serve this
purpose: their message is 64 bytes, whereas everything reaching KACS's verify
path is a 32-byte hash.

Requires OpenSSL 3.5 or later (ML-DSA support). Signing is deterministic, so
re-running against the same key reproduces byte-identical vectors; the key
itself is fresh per run and is not retained.

usage: generate-kacs-kunit-mldsa-vectors.py --out <header>
"""

import argparse
import pathlib
import subprocess
import sys
import tempfile

PUBKEY_LEN = 1952
SIG_LEN = 3309

# Fixed test messages, each standing in for a 32-byte SHA-256 content hash.
MESSAGES = {
    "TCB": bytes(range(32)),
    "ALT": bytes((0xFF - i) & 0xFF for i in range(32)),
}


def run(*args: str, stdin: bytes | None = None) -> bytes:
    proc = subprocess.run(args, input=stdin, capture_output=True)
    if proc.returncode != 0:
        sys.exit(f"command failed: {' '.join(args)}\n{proc.stderr.decode()}")
    return proc.stdout


def c_array(name: str, data: bytes) -> str:
    lines = [f"static const u8 {name}[{len(data)}] __maybe_unused = {{"]
    for off in range(0, len(data), 8):
        chunk = data[off : off + 8]
        lines.append("\t" + " ".join(f"0x{b:02x}," for b in chunk))
    lines.append("};")
    return "\n".join(lines)


def c_init_macro(name: str, data: bytes) -> str:
    """Emit the bytes as a macro usable inside a static initialiser.

    The KUnit builtin key table in signing.c needs the public key as literal
    initialiser bytes, which an array symbol cannot provide.
    """
    lines = [f"#define {name} \\"]
    for off in range(0, len(data), 8):
        chunk = data[off : off + 8]
        sep = " \\" if off + 8 < len(data) else ""
        lines.append("\t" + " ".join(f"0x{b:02x}," for b in chunk) + sep)
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    with tempfile.TemporaryDirectory() as td:
        tmp = pathlib.Path(td)
        key = tmp / "mldsa65.key"
        run("openssl", "genpkey", "-algorithm", "ML-DSA-65", "-out", str(key))

        der = run("openssl", "pkey", "-in", str(key), "-pubout", "-outform", "DER")
        pubkey = der[-PUBKEY_LEN:]
        if len(pubkey) != PUBKEY_LEN or der[-(PUBKEY_LEN + 1)] != 0:
            sys.exit("could not extract the raw public key from the SPKI")

        blocks = [
            c_init_macro("PKM_KUNIT_MLDSA65_PUBKEY_INIT", pubkey),
            c_array("pkm_kunit_mldsa65_pubkey", pubkey),
        ]
        for label, msg in MESSAGES.items():
            msg_file = tmp / f"{label}.msg"
            msg_file.write_bytes(msg)
            # Pure ML-DSA, empty context, deterministic signing.
            sig = run(
                "openssl", "pkeyutl", "-sign", "-inkey", str(key),
                "-in", str(msg_file), "-rawin",
                "-pkeyopt", "deterministic:1",
            )
            if len(sig) != SIG_LEN:
                sys.exit(f"unexpected signature length {len(sig)} for {label}")
            lower = label.lower()
            blocks.append(c_array(f"pkm_kunit_mldsa65_{lower}_hash", msg))
            blocks.append(c_array(f"pkm_kunit_mldsa65_{lower}_sig", sig))

    body = "\n\n".join(blocks)
    pathlib.Path(args.out).write_text(
        "/* SPDX-License-Identifier: GPL-2.0-only */\n"
        "/*\n"
        " * Generated by kernel/scripts/generate-kacs-kunit-mldsa-vectors.py.\n"
        " * ML-DSA-65 (FIPS 204), pure mode, empty context string, over 32-byte\n"
        " * messages standing in for SHA-256 content hashes. Do not hand-edit.\n"
        " */\n\n"
        "#ifndef PKM_KACS_KUNIT_MLDSA_VECTORS_H\n"
        "#define PKM_KACS_KUNIT_MLDSA_VECTORS_H\n\n"
        "#include <linux/compiler_attributes.h>\n#include <linux/types.h>\n\n"
        f"{body}\n\n"
        "#endif /* PKM_KACS_KUNIT_MLDSA_VECTORS_H */\n"
    )
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
