#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Generate the KACS built-in binary-signing key table header."""

import argparse
from pathlib import Path
import re
import sys


HEADER_GUARD = "PKM_KACS_BUILTIN_SIGNING_KEYS_H"


def parse_pubkey_hex(value: str) -> bytes | None:
    value = value.strip()
    if not value:
        return None
    if value.startswith(("0x", "0X")):
        value = value[2:]
    if not re.fullmatch(r"[0-9a-fA-F]{64}", value):
        raise ValueError("PKM_KACS_TCB_PUBKEY_HEX must be exactly 64 hex characters")
    return bytes.fromhex(value)


def format_key_byte_lines(key: bytes) -> list[str]:
    lines = []
    for offset in range(0, len(key), 8):
        chunk = key[offset : offset + 8]
        lines.append(", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return lines


def build_header(pubkey: bytes | None) -> str:
    rows: list[str] = ["#define PKM_KACS_BUILTIN_SIGNING_KEY_TABLE \\"]

    if pubkey is not None:
        rows.append("\t{ \\")
        rows.append("\t\t.public_key = { \\")
        for line in format_key_byte_lines(pubkey):
            rows.append(f"\t\t\t{line} \\")
        rows.append("\t\t}, \\")
        rows.append("\t\t.pip_type = cpu_to_le32(PKM_KACS_PIP_TYPE_PROTECTED), \\")
        rows.append("\t\t.pip_trust = cpu_to_le32(PKM_KACS_PIP_TRUST_PEIOS_TCB), \\")
        rows.append("\t}, \\")
    rows.append("\t{ { 0 }, 0, 0 }")

    return (
        "/* SPDX-License-Identifier: GPL-2.0-only */\n"
        "/* Generated by kernel/scripts/generate-kacs-builtin-signing-keys.py. */\n\n"
        f"#ifndef {HEADER_GUARD}\n"
        f"#define {HEADER_GUARD}\n\n"
        + "\n".join(rows)
        + "\n\n"
        f"#endif /* {HEADER_GUARD} */\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pubkey-hex", default="")
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    try:
        pubkey = parse_pubkey_hex(args.pubkey_hex)
    except ValueError as exc:
        print(f"generate-kacs-builtin-signing-keys.py: {exc}", file=sys.stderr)
        return 2

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build_header(pubkey))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
