#!/usr/bin/env python3
"""Generate the lcs-core Unicode Simple Case Folding table.

Input is the official Unicode CaseFolding.txt file for the PSD-pinned Unicode
version. Output is Rust source consumed by crates/lcs-core/src/casefold.rs.
"""

from __future__ import annotations

import argparse
import hashlib
from dataclasses import dataclass
from pathlib import Path


INCLUDED_STATUSES = {"C", "S"}


@dataclass(frozen=True)
class Mapping:
    source: int
    target: int


@dataclass(frozen=True)
class Range:
    start: int
    end: int
    mapped_start: int


def parse_casefold(path: Path) -> list[Mapping]:
    mappings: list[Mapping] = []
    seen: set[int] = set()

    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        data = line.split("#", 1)[0].strip()
        if not data:
            continue

        parts = [part.strip() for part in data.split(";")]
        if len(parts) < 3:
            raise ValueError(f"{path}:{line_number}: malformed CaseFolding row")

        source = int(parts[0], 16)
        status = parts[1]
        targets = parts[2].split()

        if status not in INCLUDED_STATUSES:
            continue
        if len(targets) != 1:
            raise ValueError(
                f"{path}:{line_number}: status {status} mapping is not simple"
            )
        if source in seen:
            raise ValueError(f"{path}:{line_number}: duplicate source U+{source:04X}")

        target = int(targets[0], 16)
        mappings.append(Mapping(source=source, target=target))
        seen.add(source)

    mappings.sort(key=lambda mapping: mapping.source)
    return mappings


def split_ranges(mappings: list[Mapping]) -> tuple[list[Range], list[Mapping]]:
    ranges: list[Range] = []
    pairs: list[Mapping] = []

    index = 0
    while index < len(mappings):
        first = mappings[index]
        end_index = index
        while end_index + 1 < len(mappings):
            current = mappings[end_index]
            candidate = mappings[end_index + 1]
            if (
                candidate.source == current.source + 1
                and candidate.target == current.target + 1
            ):
                end_index += 1
            else:
                break

        run_len = end_index - index + 1
        if run_len >= 3:
            ranges.append(
                Range(
                    start=first.source,
                    end=mappings[end_index].source,
                    mapped_start=first.target,
                )
            )
        else:
            pairs.extend(mappings[index : end_index + 1])
        index = end_index + 1

    return ranges, pairs


def write_rust(
    output: Path, source: Path, version: str, sha256: str, ranges: list[Range], pairs: list[Mapping]
) -> None:
    lines: list[str] = [
        "// @generated by tools/lcs/generate_casefold_table.py; do not edit by hand.",
        f"// Source: Unicode {version} CaseFolding.txt",
        f"// Source SHA-256: {sha256}",
        "// Included statuses: C and S. Excluded statuses: F and T.",
        "// Unicode terms of use: https://www.unicode.org/terms_of_use.html",
        "",
        "const CASE_FOLD_RANGES: &[CaseFoldRange] = &[",
    ]

    for item in ranges:
        lines.append(
            "    CaseFoldRange { "
            f"start: 0x{item.start:04X}, "
            f"end: 0x{item.end:04X}, "
            f"mapped_start: 0x{item.mapped_start:04X} "
            "},"
        )
    lines.extend(["];", "", "const CASE_FOLD_PAIRS: &[(u32, u32)] = &["])
    for item in pairs:
        lines.append(f"    (0x{item.source:04X}, 0x{item.target:04X}),")
    lines.append("];")
    lines.append("")

    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--unicode-version", default="16.0.0")
    args = parser.parse_args()

    data = args.input.read_bytes()
    sha256 = hashlib.sha256(data).hexdigest()
    mappings = parse_casefold(args.input)
    ranges, pairs = split_ranges(mappings)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    write_rust(args.out, args.input, args.unicode_version, sha256, ranges, pairs)

    print(
        f"generated {len(ranges)} ranges and {len(pairs)} pairs "
        f"from {len(mappings)} mappings; sha256={sha256}"
    )


if __name__ == "__main__":
    main()
