#!/usr/bin/env bash
# Regenerate the PKM UAPI Rust bindings from the C headers.
#
# The headers in pkm/uapi/pkm/ are the single source of truth for the PKM
# ABI. This script mirrors them into two committed, generated files:
#
#   src/ztypes.rs  struct layouts, via `bindgen` — #[repr(C)] structs with
#                  the C field names kept verbatim.
#   src/zconst.rs  every object-like #define, evaluated by the C compiler.
#                  bindgen is deliberately NOT used for constants: it
#                  silently drops ioctl macros (_IOWR ...) it cannot fold
#                  and mistypes 64-bit unsigned values. The C compiler gets
#                  both right, exactly as the Go generator does.
#
# Coverage is header-driven — every `struct NAME {` and every `#define NAME`
# is picked up — so a new ABI item cannot be silently left unbound. Both
# outputs carry the standard "DO NOT EDIT" banner.
#
# Requirements: bindgen, libclang, and a C compiler. bindgen loads libclang
# at run time via LIBCLANG_PATH; if that is unset this script probes the
# Nix store. The kernel-headers include directory is discovered from the C
# compiler, since libclang — unlike gcc — does not search it by default.
#
# Usage:
#   gen.sh            regenerate src/ztypes.rs and src/zconst.rs in place
#   gen.sh --check    regenerate into a temp dir and diff against the
#                     committed files; exit non-zero if they differ and
#                     write nothing. This is the CI drift gate.
set -euo pipefail

mode=generate
case "${1:-}" in
	--check) mode=check ;;
	"")      ;;
	*)       echo "usage: gen.sh [--check]" >&2; exit 2 ;;
esac

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"   # pkm/uapi/rust
uapi="$(cd "$here/.." && pwd)"                         # pkm/uapi
hdrs="$uapi/pkm"
cc="${CC:-cc}"
bindgen="${BINDGEN:-bindgen}"
banner="// Code generated by gen.sh; DO NOT EDIT."

# Precondition: a header outside the codegen-safe subset can make bindgen
# reproduce a struct at the wrong size. Fail before that.
bash "$uapi/check-codegen-safe.sh" >/dev/null

# bindgen loads libclang at run time and needs LIBCLANG_PATH. Prefer an
# already-set value (e.g. exported by the dev shell); else probe the Nix
# store. Setting LIBCLANG_PATH in the dev shell is the clean fix.
if [ -z "${LIBCLANG_PATH:-}" ]; then
	for d in /nix/store/*clang*-lib/lib; do
		if ls "$d"/libclang.so* >/dev/null 2>&1; then
			export LIBCLANG_PATH="$d"
			break
		fi
	done
fi
[ -n "${LIBCLANG_PATH:-}" ] || {
	echo "gen.sh: libclang not found — set LIBCLANG_PATH" >&2
	exit 1
}

# libclang, unlike gcc, does not search the kernel-headers directory by
# default. Ask the C compiler where <linux/types.h> resolves and pass that
# include path through to bindgen.
sys_inc="$(printf '#include <linux/types.h>\n' | "$cc" -E -xc - 2>/dev/null \
	| grep -om1 '/[^"]*/linux/types\.h')"
sys_inc="${sys_inc%/linux/types.h}"
[ -n "$sys_inc" ] || {
	echo "gen.sh: cannot locate <linux/types.h> via $cc" >&2
	exit 1
}

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# --- src/ztypes.rs : struct layouts via bindgen --------------------------
#
# Every struct defined in the headers is allowlisted by name; bindgen also
# pulls in the fixed-width typedefs the structs use. bindgen's first line
# names its own version — drop it for a stable, version-independent banner.
mapfile -t structs < <(grep -hE '^struct[ \t]+[A-Za-z_][A-Za-z0-9_]*[ \t]*\{' "$hdrs"/*.h \
	| sed -E 's/^struct[ \t]+([A-Za-z_][A-Za-z0-9_]*).*/\1/' | LC_ALL=C sort -u)

allow=()
for s in "${structs[@]}"; do
	allow+=(--allowlist-type "$s")
done

"$bindgen" "$hdrs/pkm.h" \
	"${allow[@]}" \
	--use-core \
	--with-derive-default \
	-- -I"$uapi" -I"$sys_inc" \
	> "$tmp/bindgen.rs"

{
	printf '%s\n\n' "$banner"
	sed -e '1{/automatically generated by rust-bindgen/d}' -e '/./,$!d' "$tmp/bindgen.rs"
} > "$tmp/ztypes.rs"

# --- src/zconst.rs : #define constants, evaluated by the C compiler ------
#
# Same macro extraction as the Go generator: object-like macros only,
# skipping function-like macros and the _UAPI_* include guards. Each macro
# becomes a Rust `pub const`, typed u32/u64 by the width the C compiler
# reports (every PKM constant is non-negative).
awk '
{
	line = $0
	while (line ~ /\\[ \t]*$/) {
		sub(/\\[ \t]*$/, "", line)
		if ((getline cont) <= 0) break
		line = line cont
	}
	if (line !~ /^[ \t]*#[ \t]*define[ \t]/) next
	sub(/^[ \t]*#[ \t]*define[ \t]+/, "", line)
	if (!match(line, /^[A-Za-z_][A-Za-z0-9_]*/)) next
	name = substr(line, 1, RLENGTH)
	after = substr(line, RLENGTH + 1)
	if (after ~ /^\(/) next        # function-like macro
	if (name ~ /^_/) next          # include guard / internal
	val = after; sub(/^[ \t]*/, "", val)
	print name "\t" (val ~ /^"/ ? "STR" : "INT")
}
' "$hdrs"/*.h | LC_ALL=C sort -u > "$tmp/macros.txt"

{
	echo '#include <pkm/pkm.h>'
	echo '#include <stdio.h>'
	echo 'int main(void)'
	echo '{'
	printf '\tfputs("%s\\n\\n", stdout);\n' "$banner"
	while IFS=$'\t' read -r name kind; do
		if [ "$kind" = STR ]; then
			printf '\tprintf("pub const %%s: &[u8; %%zu] = b\\"%%s\\";\\n", "%s", sizeof(%s) - 1, %s);\n' \
				"$name" "$name" "$name"
		else
			printf '\tprintf(sizeof(%s) <= 4 ? "pub const %%s: u32 = %%llu;\\n" : "pub const %%s: u64 = %%llu;\\n", "%s", (unsigned long long)(%s));\n' \
				"$name" "$name" "$name"
		fi
	done < "$tmp/macros.txt"
	echo '	return 0;'
	echo '}'
} > "$tmp/dumpconst.c"

"$cc" -std=c11 -I"$uapi" "$tmp/dumpconst.c" -o "$tmp/dumpconst"
"$tmp/dumpconst" | rustfmt --edition 2024 > "$tmp/zconst.rs"

# --- install or check ----------------------------------------------------
n_struct="${#structs[@]}"
n_const="$(grep -c . "$tmp/macros.txt")"
status=0
for f in ztypes.rs zconst.rs; do
	if [ "$mode" = check ]; then
		if ! diff -u "$here/src/$f" "$tmp/$f"; then
			echo "gen.sh --check: src/$f is stale — rerun gen.sh" >&2
			status=1
		fi
	else
		cp "$tmp/$f" "$here/src/$f"
	fi
done

if [ "$mode" = check ]; then
	[ "$status" -eq 0 ] &&
		echo "gen.sh --check: bindings up to date ($n_struct structs, $n_const constants)"
else
	echo "gen.sh: wrote src/ztypes.rs ($n_struct structs), src/zconst.rs ($n_const constants)"
fi
exit "$status"
