// SPDX-License-Identifier: GPL-2.0-only

//! GENERATED by tools/gen-kmes-event-table.py from the fragments in evman/.
//! Do not edit;
//! change the fragment and re-run the generator.
//!
//! The kernel's event types for the Rust emitters: the same ids, type
//! strings and tiers as `event_types.h`. Check `enabled()` before
//! building a payload; it folds to `true` for an essential type and
//! otherwise asks the C emission policy through
//! `pkm_kmes_event_enabled_ffi()`.
//!
//! ```ignore
//! if !kmes_event_types::enabled(&kmes_event_types::KACS_CAAP_SACL_SKIPPED) {
//!     continue;
//! }
//! emit(kmes_event_types::KACS_CAAP_SACL_SKIPPED.name, &payload);
//! ```

/// An event type's tier (PGSS §6.8).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u8)]
pub(crate) enum Tier {
    Essential = 0,
    Standard = 1,
    Verbose = 2,
    Debug = 3,
}

/// One kernel event type.
#[derive(Clone, Copy, Debug)]
pub(crate) struct EventType {
    /// The id the C side knows it by (`PKM_KMES_EV_*`).
    pub(crate) id: u32,
    /// The type string written to the ring.
    pub(crate) name: &'static [u8],
    pub(crate) tier: Tier,
}

pub(crate) const KACS_AUDIT_ACCESS_CHECKED: EventType = EventType {
    id: 0,
    name: b"kacs.audit.access.checked",
    tier: Tier::Essential,
};
pub(crate) const KACS_AUDIT_HANDLE_USED: EventType = EventType {
    id: 1,
    name: b"kacs.audit.handle.used",
    tier: Tier::Essential,
};
pub(crate) const KACS_AUDIT_PRIVILEGE_USED: EventType = EventType {
    id: 2,
    name: b"kacs.audit.privilege.used",
    tier: Tier::Essential,
};
pub(crate) const KACS_CAAP_SACL_SKIPPED: EventType = EventType {
    id: 3,
    name: b"kacs.caap.sacl.skipped",
    tier: Tier::Standard,
};
pub(crate) const KACS_CAAP_STAGING_DIVERGED: EventType = EventType {
    id: 4,
    name: b"kacs.caap.staging.diverged",
    tier: Tier::Standard,
};
pub(crate) const KACS_DESCRIPTOR_REJECTED: EventType = EventType {
    id: 5,
    name: b"kacs.descriptor.rejected",
    tier: Tier::Standard,
};
pub(crate) const KACS_SESSION_DESTROYED: EventType = EventType {
    id: 6,
    name: b"kacs.session.destroyed",
    tier: Tier::Essential,
};
pub(crate) const KACS_SIGNATURE_CRYPTO_FAILED: EventType = EventType {
    id: 7,
    name: b"kacs.signature.crypto.failed",
    tier: Tier::Essential,
};
pub(crate) const KMES_BUFFER_SWAP_FAILED: EventType = EventType {
    id: 8,
    name: b"kmes.buffer.swap.failed",
    tier: Tier::Standard,
};
pub(crate) const KMES_CONFIG_APPLIED: EventType = EventType {
    id: 9,
    name: b"kmes.config.applied",
    tier: Tier::Standard,
};
pub(crate) const KMES_CONFIG_REFRESH_FAILED: EventType = EventType {
    id: 10,
    name: b"kmes.config.refresh.failed",
    tier: Tier::Essential,
};
pub(crate) const KMES_CONFIG_VALUE_REJECTED: EventType = EventType {
    id: 11,
    name: b"kmes.config.value.rejected",
    tier: Tier::Essential,
};
pub(crate) const LCS_AUDIT_BACKUP_ENDED: EventType = EventType {
    id: 12,
    name: b"lcs.audit.backup.ended",
    tier: Tier::Essential,
};
pub(crate) const LCS_AUDIT_BACKUP_STARTED: EventType = EventType {
    id: 13,
    name: b"lcs.audit.backup.started",
    tier: Tier::Essential,
};
pub(crate) const LCS_AUDIT_KEY_OPENED: EventType = EventType {
    id: 14,
    name: b"lcs.audit.key.opened",
    tier: Tier::Essential,
};
pub(crate) const LCS_AUDIT_RESTORE_ENDED: EventType = EventType {
    id: 15,
    name: b"lcs.audit.restore.ended",
    tier: Tier::Essential,
};
pub(crate) const LCS_AUDIT_RESTORE_STARTED: EventType = EventType {
    id: 16,
    name: b"lcs.audit.restore.started",
    tier: Tier::Essential,
};
pub(crate) const LCS_CONFIG_VALUE_REJECTED: EventType = EventType {
    id: 17,
    name: b"lcs.config.value.rejected",
    tier: Tier::Essential,
};
pub(crate) const LCS_SOURCE_RESPONSE_REJECTED: EventType = EventType {
    id: 18,
    name: b"lcs.source.response.rejected",
    tier: Tier::Essential,
};
pub(crate) const NTFE_VERDICT_REPORTED: EventType = EventType {
    id: 19,
    name: b"ntfe.verdict.reported",
    tier: Tier::Essential,
};
pub(crate) const STRATAFS_FILE_COPIED_UP: EventType = EventType {
    id: 20,
    name: b"stratafs.file.copied-up",
    tier: Tier::Standard,
};
pub(crate) const STRATAFS_MUTATION_REFUSED: EventType = EventType {
    id: 21,
    name: b"stratafs.mutation.refused",
    tier: Tier::Standard,
};

/// How many kernel event types there are.
pub(crate) const COUNT: u32 = 22;

extern "C" {
    fn pkm_kmes_event_enabled_ffi(id: u32) -> bool;
}

/// Whether `event` is switched on. An essential type is always on and
/// never reads the policy; any other asks the kernel's cached policy.
#[inline]
pub(crate) fn enabled(event: &EventType) -> bool {
    if event.tier == Tier::Essential {
        return true;
    }
    // SAFETY: a plain read of the published mask; any id is accepted.
    unsafe { pkm_kmes_event_enabled_ffi(event.id) }
}
