/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * GENERATED by tools/gen-kmes-event-table.py from the fragments in evman/.
 * Do not edit;
 * change the fragment and re-run the generator.
 *
 * Every event type the kernel writes, with its tier (PGSS §6.8). The
 * emission policy (event_policy.h) keeps one enabled bit per id.
 *
 * How an emitter uses it. The check is the emitter's first statement,
 * before any payload sizing, building or allocation:
 *
 *	if (!pkm_kmes_event_enabled(PKM_KMES_EV_KMES_BUFFER_SWAP_FAILED))
 *		return 0;
 *	...
 *	pkm_kmes_emit_kernel(KMES_ORIGIN_KMES,
 *			     PKM_KMES_EV_KMES_BUFFER_SWAP_FAILED_TYPE,
 *			     sizeof(PKM_KMES_EV_KMES_BUFFER_SWAP_FAILED_TYPE) - 1,
 *			     payload, len);
 *
 * The id must be a compile-time constant: for an essential type the
 * check then folds to true and never reads the policy (§6.9 MUST).
 * Essential emitters may leave the call out, but calling it uniformly
 * keeps a later re-tier a one-line fragment change. The policy decides
 * first and any gating (a SACL, an alarm mask, a REPORT level) second;
 * the two combine by AND. Rust emitters use event_types.rs, whose
 * enabled() calls the same check through pkm_kmes_event_enabled_ffi().
 */
#ifndef _SECURITY_PKM_KMES_EVENT_TYPES_H
#define _SECURITY_PKM_KMES_EVENT_TYPES_H

#include <linux/build_bug.h>
#include <linux/types.h>

enum pkm_kmes_event_tier {
	PKM_KMES_EV_TIER_ESSENTIAL = 0,
	PKM_KMES_EV_TIER_STANDARD = 1,
	PKM_KMES_EV_TIER_VERBOSE = 2,
	PKM_KMES_EV_TIER_DEBUG = 3,
};

enum pkm_kmes_event_id {
	PKM_KMES_EV_KACS_AUDIT_ACCESS_CHECKED    = 0, /* essential, kacs.evman */
	PKM_KMES_EV_KACS_AUDIT_HANDLE_USED       = 1, /* essential, kacs.evman */
	PKM_KMES_EV_KACS_AUDIT_PRIVILEGE_USED    = 2, /* essential, kacs.evman */
	PKM_KMES_EV_KACS_CAAP_SACL_SKIPPED       = 3, /* standard, kacs.evman */
	PKM_KMES_EV_KACS_CAAP_STAGING_DIVERGED   = 4, /* standard, kacs.evman */
	PKM_KMES_EV_KACS_DESCRIPTOR_REJECTED     = 5, /* standard, kacs.evman */
	PKM_KMES_EV_KACS_SESSION_DESTROYED       = 6, /* essential, kacs.evman */
	PKM_KMES_EV_KACS_SIGNATURE_CRYPTO_FAILED = 7, /* essential, kacs.evman */
	PKM_KMES_EV_KMES_BUFFER_SWAP_FAILED      = 8, /* standard, kmes.evman */
	PKM_KMES_EV_KMES_CONFIG_APPLIED          = 9, /* standard, kmes.evman */
	PKM_KMES_EV_KMES_CONFIG_REFRESH_FAILED   = 10, /* essential, kmes.evman */
	PKM_KMES_EV_KMES_CONFIG_VALUE_REJECTED   = 11, /* essential, kmes.evman */
	PKM_KMES_EV_LCS_AUDIT_BACKUP_ENDED       = 12, /* essential, lcs.evman */
	PKM_KMES_EV_LCS_AUDIT_BACKUP_STARTED     = 13, /* essential, lcs.evman */
	PKM_KMES_EV_LCS_AUDIT_KEY_OPENED         = 14, /* essential, lcs.evman */
	PKM_KMES_EV_LCS_AUDIT_RESTORE_ENDED      = 15, /* essential, lcs.evman */
	PKM_KMES_EV_LCS_AUDIT_RESTORE_STARTED    = 16, /* essential, lcs.evman */
	PKM_KMES_EV_LCS_CONFIG_VALUE_REJECTED    = 17, /* essential, lcs.evman */
	PKM_KMES_EV_LCS_SOURCE_RESPONSE_REJECTED = 18, /* essential, lcs.evman */
	PKM_KMES_EV_NTFE_VERDICT_REPORTED        = 19, /* essential, ntfe.evman */
	PKM_KMES_EV_STRATAFS_FILE_COPIED_UP      = 20, /* standard, stratafs.evman */
	PKM_KMES_EV_STRATAFS_MUTATION_REFUSED    = 21, /* standard, stratafs.evman */
	PKM_KMES_EV_COUNT                        = 22,
};

static_assert(PKM_KMES_EV_COUNT <= 64,
	      "the enabled mask is one u64; move it behind RCU first");

/* The type strings, for pkm_kmes_emit_kernel(). */
#define PKM_KMES_EV_KACS_AUDIT_ACCESS_CHECKED_TYPE "kacs.audit.access.checked"
#define PKM_KMES_EV_KACS_AUDIT_HANDLE_USED_TYPE "kacs.audit.handle.used"
#define PKM_KMES_EV_KACS_AUDIT_PRIVILEGE_USED_TYPE "kacs.audit.privilege.used"
#define PKM_KMES_EV_KACS_CAAP_SACL_SKIPPED_TYPE "kacs.caap.sacl.skipped"
#define PKM_KMES_EV_KACS_CAAP_STAGING_DIVERGED_TYPE "kacs.caap.staging.diverged"
#define PKM_KMES_EV_KACS_DESCRIPTOR_REJECTED_TYPE "kacs.descriptor.rejected"
#define PKM_KMES_EV_KACS_SESSION_DESTROYED_TYPE "kacs.session.destroyed"
#define PKM_KMES_EV_KACS_SIGNATURE_CRYPTO_FAILED_TYPE "kacs.signature.crypto.failed"
#define PKM_KMES_EV_KMES_BUFFER_SWAP_FAILED_TYPE "kmes.buffer.swap.failed"
#define PKM_KMES_EV_KMES_CONFIG_APPLIED_TYPE "kmes.config.applied"
#define PKM_KMES_EV_KMES_CONFIG_REFRESH_FAILED_TYPE "kmes.config.refresh.failed"
#define PKM_KMES_EV_KMES_CONFIG_VALUE_REJECTED_TYPE "kmes.config.value.rejected"
#define PKM_KMES_EV_LCS_AUDIT_BACKUP_ENDED_TYPE "lcs.audit.backup.ended"
#define PKM_KMES_EV_LCS_AUDIT_BACKUP_STARTED_TYPE "lcs.audit.backup.started"
#define PKM_KMES_EV_LCS_AUDIT_KEY_OPENED_TYPE "lcs.audit.key.opened"
#define PKM_KMES_EV_LCS_AUDIT_RESTORE_ENDED_TYPE "lcs.audit.restore.ended"
#define PKM_KMES_EV_LCS_AUDIT_RESTORE_STARTED_TYPE "lcs.audit.restore.started"
#define PKM_KMES_EV_LCS_CONFIG_VALUE_REJECTED_TYPE "lcs.config.value.rejected"
#define PKM_KMES_EV_LCS_SOURCE_RESPONSE_REJECTED_TYPE "lcs.source.response.rejected"
#define PKM_KMES_EV_NTFE_VERDICT_REPORTED_TYPE "ntfe.verdict.reported"
#define PKM_KMES_EV_STRATAFS_FILE_COPIED_UP_TYPE "stratafs.file.copied-up"
#define PKM_KMES_EV_STRATAFS_MUTATION_REFUSED_TYPE "stratafs.mutation.refused"

/*
 * Each type's tier. With a constant id this folds at compile time,
 * which is what lets pkm_kmes_event_enabled() skip the policy for an
 * essential type without a load.
 */
static __always_inline enum pkm_kmes_event_tier
pkm_kmes_event_tier(enum pkm_kmes_event_id id)
{
	switch (id) {
	case PKM_KMES_EV_KACS_AUDIT_ACCESS_CHECKED:
	case PKM_KMES_EV_KACS_AUDIT_HANDLE_USED:
	case PKM_KMES_EV_KACS_AUDIT_PRIVILEGE_USED:
	case PKM_KMES_EV_KACS_SESSION_DESTROYED:
	case PKM_KMES_EV_KACS_SIGNATURE_CRYPTO_FAILED:
	case PKM_KMES_EV_KMES_CONFIG_REFRESH_FAILED:
	case PKM_KMES_EV_KMES_CONFIG_VALUE_REJECTED:
	case PKM_KMES_EV_LCS_AUDIT_BACKUP_ENDED:
	case PKM_KMES_EV_LCS_AUDIT_BACKUP_STARTED:
	case PKM_KMES_EV_LCS_AUDIT_KEY_OPENED:
	case PKM_KMES_EV_LCS_AUDIT_RESTORE_ENDED:
	case PKM_KMES_EV_LCS_AUDIT_RESTORE_STARTED:
	case PKM_KMES_EV_LCS_CONFIG_VALUE_REJECTED:
	case PKM_KMES_EV_LCS_SOURCE_RESPONSE_REJECTED:
	case PKM_KMES_EV_NTFE_VERDICT_REPORTED:
		return PKM_KMES_EV_TIER_ESSENTIAL;
	case PKM_KMES_EV_KACS_CAAP_SACL_SKIPPED:
	case PKM_KMES_EV_KACS_CAAP_STAGING_DIVERGED:
	case PKM_KMES_EV_KACS_DESCRIPTOR_REJECTED:
	case PKM_KMES_EV_KMES_BUFFER_SWAP_FAILED:
	case PKM_KMES_EV_KMES_CONFIG_APPLIED:
	case PKM_KMES_EV_STRATAFS_FILE_COPIED_UP:
	case PKM_KMES_EV_STRATAFS_MUTATION_REFUSED:
		return PKM_KMES_EV_TIER_STANDARD;
	default:
		/* Not a kernel type: never let the policy hide it. */
		return PKM_KMES_EV_TIER_ESSENTIAL;
	}
}

/*
 * The mask in force before the policy has ever been read (§6.9: decide
 * by tier alone): essential and standard on, verbose and debug off.
 */
#define PKM_KMES_EV_DEFAULT_MASK 0x00000000003fffffULL

#define PKM_KMES_EV_NODE_COUNT 54
#define PKM_KMES_EV_ROOT_COUNT 5

#ifdef PKM_KMES_EVENT_TYPES_WANT_TABLES
/*
 * The tables the policy walk needs, compiled into event_policy.c alone.
 *
 * The nodes are the trie of every type's segments beneath
 * Machine\Generic\Events, in pre-order: a node's parent always comes
 * before it, and parent -1 is the Events key itself. A type's leaf is
 * the node its last segment names.
 */
struct pkm_kmes_event_node {
	const char *segment;
	u8 segment_len;
	s16 parent;
};

static const struct pkm_kmes_event_node
	pkm_kmes_event_nodes[PKM_KMES_EV_NODE_COUNT] = {
	[0] = { "kacs", 4, -1 },
	[1] = { "audit", 5, 0 },
	[2] = { "access", 6, 1 },
	[3] = { "checked", 7, 2 },
	[4] = { "handle", 6, 1 },
	[5] = { "used", 4, 4 },
	[6] = { "privilege", 9, 1 },
	[7] = { "used", 4, 6 },
	[8] = { "caap", 4, 0 },
	[9] = { "sacl", 4, 8 },
	[10] = { "skipped", 7, 9 },
	[11] = { "staging", 7, 8 },
	[12] = { "diverged", 8, 11 },
	[13] = { "descriptor", 10, 0 },
	[14] = { "rejected", 8, 13 },
	[15] = { "session", 7, 0 },
	[16] = { "destroyed", 9, 15 },
	[17] = { "signature", 9, 0 },
	[18] = { "crypto", 6, 17 },
	[19] = { "failed", 6, 18 },
	[20] = { "kmes", 4, -1 },
	[21] = { "buffer", 6, 20 },
	[22] = { "swap", 4, 21 },
	[23] = { "failed", 6, 22 },
	[24] = { "config", 6, 20 },
	[25] = { "applied", 7, 24 },
	[26] = { "refresh", 7, 24 },
	[27] = { "failed", 6, 26 },
	[28] = { "value", 5, 24 },
	[29] = { "rejected", 8, 28 },
	[30] = { "lcs", 3, -1 },
	[31] = { "audit", 5, 30 },
	[32] = { "backup", 6, 31 },
	[33] = { "ended", 5, 32 },
	[34] = { "started", 7, 32 },
	[35] = { "key", 3, 31 },
	[36] = { "opened", 6, 35 },
	[37] = { "restore", 7, 31 },
	[38] = { "ended", 5, 37 },
	[39] = { "started", 7, 37 },
	[40] = { "config", 6, 30 },
	[41] = { "value", 5, 40 },
	[42] = { "rejected", 8, 41 },
	[43] = { "source", 6, 30 },
	[44] = { "response", 8, 43 },
	[45] = { "rejected", 8, 44 },
	[46] = { "ntfe", 4, -1 },
	[47] = { "verdict", 7, 46 },
	[48] = { "reported", 8, 47 },
	[49] = { "stratafs", 8, -1 },
	[50] = { "file", 4, 49 },
	[51] = { "copied-up", 9, 50 },
	[52] = { "mutation", 8, 49 },
	[53] = { "refused", 7, 52 },
};

static const u16 pkm_kmes_event_leaf[PKM_KMES_EV_COUNT] = {
	[PKM_KMES_EV_KACS_AUDIT_ACCESS_CHECKED] = 3,
	[PKM_KMES_EV_KACS_AUDIT_HANDLE_USED] = 5,
	[PKM_KMES_EV_KACS_AUDIT_PRIVILEGE_USED] = 7,
	[PKM_KMES_EV_KACS_CAAP_SACL_SKIPPED] = 10,
	[PKM_KMES_EV_KACS_CAAP_STAGING_DIVERGED] = 12,
	[PKM_KMES_EV_KACS_DESCRIPTOR_REJECTED] = 14,
	[PKM_KMES_EV_KACS_SESSION_DESTROYED] = 16,
	[PKM_KMES_EV_KACS_SIGNATURE_CRYPTO_FAILED] = 19,
	[PKM_KMES_EV_KMES_BUFFER_SWAP_FAILED] = 23,
	[PKM_KMES_EV_KMES_CONFIG_APPLIED] = 25,
	[PKM_KMES_EV_KMES_CONFIG_REFRESH_FAILED] = 27,
	[PKM_KMES_EV_KMES_CONFIG_VALUE_REJECTED] = 29,
	[PKM_KMES_EV_LCS_AUDIT_BACKUP_ENDED] = 33,
	[PKM_KMES_EV_LCS_AUDIT_BACKUP_STARTED] = 34,
	[PKM_KMES_EV_LCS_AUDIT_KEY_OPENED] = 36,
	[PKM_KMES_EV_LCS_AUDIT_RESTORE_ENDED] = 38,
	[PKM_KMES_EV_LCS_AUDIT_RESTORE_STARTED] = 39,
	[PKM_KMES_EV_LCS_CONFIG_VALUE_REJECTED] = 42,
	[PKM_KMES_EV_LCS_SOURCE_RESPONSE_REJECTED] = 45,
	[PKM_KMES_EV_NTFE_VERDICT_REPORTED] = 48,
	[PKM_KMES_EV_STRATAFS_FILE_COPIED_UP] = 51,
	[PKM_KMES_EV_STRATAFS_MUTATION_REFUSED] = 53,
};

static const char * const pkm_kmes_event_names[PKM_KMES_EV_COUNT] = {
	[PKM_KMES_EV_KACS_AUDIT_ACCESS_CHECKED] = PKM_KMES_EV_KACS_AUDIT_ACCESS_CHECKED_TYPE,
	[PKM_KMES_EV_KACS_AUDIT_HANDLE_USED] = PKM_KMES_EV_KACS_AUDIT_HANDLE_USED_TYPE,
	[PKM_KMES_EV_KACS_AUDIT_PRIVILEGE_USED] = PKM_KMES_EV_KACS_AUDIT_PRIVILEGE_USED_TYPE,
	[PKM_KMES_EV_KACS_CAAP_SACL_SKIPPED] = PKM_KMES_EV_KACS_CAAP_SACL_SKIPPED_TYPE,
	[PKM_KMES_EV_KACS_CAAP_STAGING_DIVERGED] = PKM_KMES_EV_KACS_CAAP_STAGING_DIVERGED_TYPE,
	[PKM_KMES_EV_KACS_DESCRIPTOR_REJECTED] = PKM_KMES_EV_KACS_DESCRIPTOR_REJECTED_TYPE,
	[PKM_KMES_EV_KACS_SESSION_DESTROYED] = PKM_KMES_EV_KACS_SESSION_DESTROYED_TYPE,
	[PKM_KMES_EV_KACS_SIGNATURE_CRYPTO_FAILED] = PKM_KMES_EV_KACS_SIGNATURE_CRYPTO_FAILED_TYPE,
	[PKM_KMES_EV_KMES_BUFFER_SWAP_FAILED] = PKM_KMES_EV_KMES_BUFFER_SWAP_FAILED_TYPE,
	[PKM_KMES_EV_KMES_CONFIG_APPLIED] = PKM_KMES_EV_KMES_CONFIG_APPLIED_TYPE,
	[PKM_KMES_EV_KMES_CONFIG_REFRESH_FAILED] = PKM_KMES_EV_KMES_CONFIG_REFRESH_FAILED_TYPE,
	[PKM_KMES_EV_KMES_CONFIG_VALUE_REJECTED] = PKM_KMES_EV_KMES_CONFIG_VALUE_REJECTED_TYPE,
	[PKM_KMES_EV_LCS_AUDIT_BACKUP_ENDED] = PKM_KMES_EV_LCS_AUDIT_BACKUP_ENDED_TYPE,
	[PKM_KMES_EV_LCS_AUDIT_BACKUP_STARTED] = PKM_KMES_EV_LCS_AUDIT_BACKUP_STARTED_TYPE,
	[PKM_KMES_EV_LCS_AUDIT_KEY_OPENED] = PKM_KMES_EV_LCS_AUDIT_KEY_OPENED_TYPE,
	[PKM_KMES_EV_LCS_AUDIT_RESTORE_ENDED] = PKM_KMES_EV_LCS_AUDIT_RESTORE_ENDED_TYPE,
	[PKM_KMES_EV_LCS_AUDIT_RESTORE_STARTED] = PKM_KMES_EV_LCS_AUDIT_RESTORE_STARTED_TYPE,
	[PKM_KMES_EV_LCS_CONFIG_VALUE_REJECTED] = PKM_KMES_EV_LCS_CONFIG_VALUE_REJECTED_TYPE,
	[PKM_KMES_EV_LCS_SOURCE_RESPONSE_REJECTED] = PKM_KMES_EV_LCS_SOURCE_RESPONSE_REJECTED_TYPE,
	[PKM_KMES_EV_NTFE_VERDICT_REPORTED] = PKM_KMES_EV_NTFE_VERDICT_REPORTED_TYPE,
	[PKM_KMES_EV_STRATAFS_FILE_COPIED_UP] = PKM_KMES_EV_STRATAFS_FILE_COPIED_UP_TYPE,
	[PKM_KMES_EV_STRATAFS_MUTATION_REFUSED] = PKM_KMES_EV_STRATAFS_MUTATION_REFUSED_TYPE,
};

/* The first segments: the only keys under Events the kernel watches. */
static const char * const
	pkm_kmes_event_roots[PKM_KMES_EV_ROOT_COUNT] = {
	"kacs",
	"kmes",
	"lcs",
	"ntfe",
	"stratafs",
};
#endif /* PKM_KMES_EVENT_TYPES_WANT_TABLES */

#endif /* _SECURITY_PKM_KMES_EVENT_TYPES_H */
