// Well-known Security Identifiers referenced throughout KACS.
//
// These are the same SIDs used by Windows and Samba. Binary-compatible.
// See MS-DTYP §2.4.2.4 for the full catalog.

use crate::sid::Sid;

// --- Authorities ---
// The identifier authority is the 6-byte field after the revision.

pub const AUTHORITY_NULL: u64 = 0;
pub const AUTHORITY_WORLD: u64 = 1;
pub const AUTHORITY_LOCAL: u64 = 2;
pub const AUTHORITY_CREATOR: u64 = 3;
pub const AUTHORITY_NT: u64 = 5;
pub const AUTHORITY_APP_PACKAGE: u64 = 15;
pub const AUTHORITY_MANDATORY_LABEL: u64 = 16;
pub const AUTHORITY_PROCESS_TRUST: u64 = 19;

// --- Universal well-known SIDs ---

/// S-1-0-0 — NULL SID. No security principal.
pub fn null() -> Sid {
    Sid::new(AUTHORITY_NULL, &[0])
}

/// S-1-1-0 — Everyone. Matches all principals.
pub fn everyone() -> Sid {
    Sid::new(AUTHORITY_WORLD, &[0])
}

/// S-1-2-0 — Local. All users who log on locally.
pub fn local() -> Sid {
    Sid::new(AUTHORITY_LOCAL, &[0])
}

// --- Creator SIDs (substituted during inheritance §9.5) ---

/// S-1-3-0 — Creator Owner. Replaced with the creating principal's SID.
pub fn creator_owner() -> Sid {
    Sid::new(AUTHORITY_CREATOR, &[0])
}

/// S-1-3-1 — Creator Group. Replaced with the creating principal's group.
pub fn creator_group() -> Sid {
    Sid::new(AUTHORITY_CREATOR, &[1])
}

/// S-1-3-4 — Owner Rights. Suppresses/replaces owner implicit grants (§11.4).
pub fn owner_rights() -> Sid {
    Sid::new(AUTHORITY_CREATOR, &[4])
}

// --- NT Authority SIDs ---

/// S-1-5-7 — Anonymous. Identity for anonymous connections.
pub fn anonymous() -> Sid {
    Sid::new(AUTHORITY_NT, &[7])
}

/// S-1-5-10 — Principal Self. Matches the object's associated principal (§11.8).
pub fn principal_self() -> Sid {
    Sid::new(AUTHORITY_NT, &[10])
}

/// S-1-5-11 — Authenticated Users. All authenticated principals.
pub fn authenticated_users() -> Sid {
    Sid::new(AUTHORITY_NT, &[11])
}

/// S-1-5-18 — Local System (SYSTEM). Highest privilege built-in identity.
pub fn system() -> Sid {
    Sid::new(AUTHORITY_NT, &[18])
}

/// S-1-5-19 — Local Service. Minimal privilege service identity.
pub fn local_service() -> Sid {
    Sid::new(AUTHORITY_NT, &[19])
}

/// S-1-5-20 — Network Service. Network-capable service identity.
pub fn network_service() -> Sid {
    Sid::new(AUTHORITY_NT, &[20])
}

// --- BUILTIN domain SIDs (S-1-5-32-*) ---

/// S-1-5-32-544 — BUILTIN\Administrators.
pub fn administrators() -> Sid {
    Sid::new(AUTHORITY_NT, &[32, 544])
}

/// S-1-5-32-545 — BUILTIN\Users.
pub fn users() -> Sid {
    Sid::new(AUTHORITY_NT, &[32, 545])
}

/// S-1-5-32-546 — BUILTIN\Guests.
pub fn guests() -> Sid {
    Sid::new(AUTHORITY_NT, &[32, 546])
}

// --- Logon type SIDs ---

/// S-1-5-2 — Network. Added to tokens from network logons.
pub fn network() -> Sid {
    Sid::new(AUTHORITY_NT, &[2])
}

/// S-1-5-4 — Interactive. Added to tokens from interactive logons.
pub fn interactive() -> Sid {
    Sid::new(AUTHORITY_NT, &[4])
}

/// S-1-5-6 — Service. Added to tokens for service logons.
pub fn service() -> Sid {
    Sid::new(AUTHORITY_NT, &[6])
}

// --- Logon session SIDs (S-1-5-5-X-Y, generated per session) ---

/// S-1-5-5-{high}-{low} — Logon session SID. Generated by kacs_create_session.
pub fn logon_sid(high: u32, low: u32) -> Sid {
    Sid::new(AUTHORITY_NT, &[5, high, low])
}

// --- Per-service SIDs (S-1-5-80-*, hash-derived) ---

/// S-1-5-80-{h0}-{h1}-{h2}-{h3}-{h4} — NT SERVICE SID.
/// Sub-authorities derived from SHA-1 hash of the service name.
pub fn service_sid(hash_parts: [u32; 5]) -> Sid {
    Sid::new(AUTHORITY_NT, &[80, hash_parts[0], hash_parts[1], hash_parts[2], hash_parts[3], hash_parts[4]])
}

// --- Mandatory integrity labels (S-1-16-*) ---

/// S-1-16-0 — Untrusted integrity.
pub fn integrity_untrusted() -> Sid {
    Sid::new(AUTHORITY_MANDATORY_LABEL, &[0])
}

/// S-1-16-4096 — Low integrity.
pub fn integrity_low() -> Sid {
    Sid::new(AUTHORITY_MANDATORY_LABEL, &[4096])
}

/// S-1-16-8192 — Medium integrity (default).
pub fn integrity_medium() -> Sid {
    Sid::new(AUTHORITY_MANDATORY_LABEL, &[8192])
}

/// S-1-16-12288 — High integrity.
pub fn integrity_high() -> Sid {
    Sid::new(AUTHORITY_MANDATORY_LABEL, &[12288])
}

/// S-1-16-16384 — System integrity.
pub fn integrity_system() -> Sid {
    Sid::new(AUTHORITY_MANDATORY_LABEL, &[16384])
}

// --- Process trust labels (S-1-19-type-trust) §11.15 ---

/// S-1-19-{type}-{trust} — Process trust label SID.
pub fn trust_label(pip_type: u32, pip_trust: u32) -> Sid {
    Sid::new(AUTHORITY_PROCESS_TRUST, &[pip_type, pip_trust])
}

// PIP type values (§11.15)
pub const PIP_TYPE_NONE: u32 = 0;
pub const PIP_TYPE_PROTECTED: u32 = 512;
pub const PIP_TYPE_ISOLATED: u32 = 1024;

// PIP trust values (§11.15)
pub const PIP_TRUST_NONE: u32 = 0;
pub const PIP_TRUST_AUTHENTICODE: u32 = 1024;
pub const PIP_TRUST_ANTIMALWARE: u32 = 1536;
pub const PIP_TRUST_APP: u32 = 2048;
pub const PIP_TRUST_PEIOS: u32 = 4096;
pub const PIP_TRUST_PEIOS_TCB: u32 = 8192;

// --- Application confinement (S-1-15-2-*, S-1-15-3-*) §11.14 ---

/// S-1-15-2-1 — ALL_APP_PACKAGES. Normal confinement access.
pub fn all_app_packages() -> Sid {
    Sid::new(AUTHORITY_APP_PACKAGE, &[2, 1])
}

/// S-1-15-2-2 — ALL_RESTRICTED_APP_PACKAGES. Strict confinement access.
pub fn all_restricted_app_packages() -> Sid {
    Sid::new(AUTHORITY_APP_PACKAGE, &[2, 2])
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::string::ToString;

    #[test]
    fn system_sid_string() {
        assert_eq!(system().to_string(), "S-1-5-18");
    }

    #[test]
    fn administrators_sid_string() {
        assert_eq!(administrators().to_string(), "S-1-5-32-544");
    }

    #[test]
    fn everyone_sid_string() {
        assert_eq!(everyone().to_string(), "S-1-1-0");
    }

    #[test]
    fn integrity_medium_string() {
        assert_eq!(integrity_medium().to_string(), "S-1-16-8192");
    }

    #[test]
    fn trust_label_string() {
        let label = trust_label(PIP_TYPE_PROTECTED, PIP_TRUST_PEIOS);
        assert_eq!(label.to_string(), "S-1-19-512-4096");
    }

    #[test]
    fn owner_rights_string() {
        assert_eq!(owner_rights().to_string(), "S-1-3-4");
    }

    #[test]
    fn principal_self_string() {
        assert_eq!(principal_self().to_string(), "S-1-5-10");
    }

    #[test]
    fn logon_sid_string() {
        assert_eq!(logon_sid(0, 0).to_string(), "S-1-5-5-0-0");
        assert_eq!(logon_sid(123, 456).to_string(), "S-1-5-5-123-456");
    }

    #[test]
    fn well_known_sids_round_trip() {
        // Every well-known SID should survive binary round-trip
        let sids = [
            null(), everyone(), local(), creator_owner(), creator_group(),
            owner_rights(), anonymous(), principal_self(),
            authenticated_users(), system(), local_service(),
            network_service(), administrators(), users(), guests(),
            network(), interactive(), service(),
            integrity_untrusted(), integrity_low(), integrity_medium(),
            integrity_high(), integrity_system(),
            all_app_packages(), all_restricted_app_packages(),
        ];
        for sid in &sids {
            let bytes = sid.to_bytes();
            let parsed = Sid::from_bytes(&bytes).unwrap();
            assert_eq!(sid, &parsed);
        }
    }
}
