// Code generated by gen.sh; DO NOT EDIT.

package uapi

type Kacs_access_check_args struct {
	Caller_size              uint32
	Token_fd                 int32
	Sd_ptr                   uint64
	Sd_len                   uint32
	Desired_access           uint32
	Mapping_read             uint32
	Mapping_write            uint32
	Mapping_execute          uint32
	Mapping_all              uint32
	Self_sid_ptr             uint64
	Self_sid_len             uint32
	Privilege_intent         uint32
	Object_tree_ptr          uint64
	Object_tree_count        uint32
	_                        uint32
	Local_claims_ptr         uint64
	Local_claims_len         uint32
	_                        uint32
	Granted_out_ptr          uint64
	Pip_type                 uint32
	Pip_trust                uint32
	Audit_context_ptr        uint64
	Audit_context_len        uint32
	_                        uint32
	Continuous_audit_out_ptr uint64
	Staging_mismatch_out_ptr uint64
}
type Kacs_adjust_default_args struct {
	Dacl_ptr    uint64
	Dacl_len    uint32
	Owner_index uint16
	Group_index uint16
}
type Kacs_adjust_groups_args struct {
	Count          uint32
	_              uint32
	Data_ptr       uint64
	Previous_state uint64
}
type Kacs_adjust_privs_args struct {
	Count            uint32
	_                uint32
	Data_ptr         uint64
	Previous_enabled uint64
}
type Kacs_duplicate_args struct {
	Access_mask         uint32
	Token_type          uint32
	Impersonation_level uint32
	Result_fd           int32
}
type Kacs_generic_mapping struct {
	Read    uint32
	Write   uint32
	Execute uint32
	All     uint32
}
type Kacs_get_linked_token_args struct {
	Result_fd int32
}
type Kacs_group_entry struct {
	Index  uint32
	Enable uint32
}
type Kacs_link_tokens_args struct {
	Elevated_fd int32
	Filtered_fd int32
	Session_id  uint64
}
type Kacs_mount_policy_args struct {
	Policy          uint32
	Flags           uint32
	Generation      uint32
	_               uint32
	Template_sd_ptr uint64
	Template_sd_len uint32
	_               uint32
}
type Kacs_node_result struct {
	Granted uint32
	Status  int32
}
type Kacs_object_type_entry struct {
	Level uint16
	_     uint16
	Guid  [16]uint8
}
type Kacs_open_how struct {
	Desired_access     uint32
	Create_disposition uint32
	Create_options     uint32
	Flags              uint32
	Sd_ptr             uint64
	Sd_len             uint32
	_                  uint32
}
type Kacs_priv_entry struct {
	Luid       uint32
	Attributes uint32
}
type Kacs_query_args struct {
	Token_class uint32
	Buf_len     uint32
	Buf_ptr     uint64
}
type Kacs_restrict_args struct {
	Privs_to_delete   uint64
	Num_deny_indices  uint32
	Num_restrict_sids uint32
	Data_len          uint32
	Flags             uint32
	Data_ptr          uint64
	Result_fd         int32
	_                 uint32
}
type Kmes_emit_entry struct {
	Event_type     uint64
	Event_type_len uint16
	_              [6]uint8
	Payload        uint64
	Payload_len    uint32
	_              [4]uint8
}
