// SPDX-License-Identifier: GPL-2.0-only
#ifndef PKM_KACS_KUNIT_COMMON_H
#define PKM_KACS_KUNIT_COMMON_H

/* Generated by tools split of the monolithic kunit.c — see git log. */

// SPDX-License-Identifier: GPL-2.0-only
/*
 * PKM KACS KUnit suite.
 *
 * Exercises the full C -> Rust -> kacs-core seam in-kernel: token, process,
 * and file enforcement; the CAAP cache; and TCB-gated CAAP signing. These are
 * live security semantics, not a plumbing stub.
 *
 * The suite identifier below is still "pkm_kunit_scaffold" for historical
 * reasons; it is kept stable because the smoke gate
 * (kernel/check-kunit-scaffold.sh) matches the summary line on that name.
 */

#include <crypto/sha2.h>

#include <crypto/sig.h>


#include <kunit/test.h>

#include <linux/anon_inodes.h>

#include <linux/build_bug.h>

#include <linux/capability.h>

#include <linux/cpumask.h>

#include <linux/cred.h>

#include <linux/elf.h>

#include <linux/err.h>

#include <linux/errno.h>

#include <linux/falloc.h>

#include <linux/fdtable.h>

#include <linux/fcntl.h>

#include <linux/fiemap.h>

#include <linux/file.h>

#include <linux/fs.h>

#include <linux/fscrypt.h>

#include <linux/kernel.h>

#include <linux/magic.h>

#include <linux/mm.h>

#include <linux/mman.h>

#include <linux/net.h>

#include <linux/pid.h>

#include <linux/prctl.h>

#include <linux/ptrace.h>

#include <linux/sched.h>

#include <linux/sched/coredump.h>

#include <linux/slab.h>

#include <linux/socket.h>

#include <linux/stddef.h>

#include <linux/string.h>

#include <linux/syscalls.h>

#include <linux/types.h>

#include <linux/xattr.h>


#include <asm/ioctls.h>


#include "access_check.h"

#include "caap_cache.h"

#include "../kmes/kmes.h"

#include "token_fd.h"

#include "token_runtime.h"


#ifndef PTRACE_MODE_PIDFD_OPEN

#define PTRACE_MODE_PIDFD_OPEN 0x40

#endif


#ifndef PTRACE_MODE_PROC_QUERY_LIMITED

#define PTRACE_MODE_PROC_QUERY_LIMITED 0x80

#endif


#ifndef PTRACE_MODE_PROC_QUERY_INFORMATION

#define PTRACE_MODE_PROC_QUERY_INFORMATION 0x100

#endif


#define PKM_KUNIT_SYSTEM_READ_CONTROL_GRANT \
	(KACS_ACCESS_READ_CONTROL | KACS_ACCESS_WRITE_DAC | \
	 KACS_ACCESS_ACCESS_SYSTEM_SECURITY)

#define PKM_KUNIT_CAAP_PRIVILEGE_GRANT KACS_ACCESS_ACCESS_SYSTEM_SECURITY

#define PKM_KUNIT_CAAP_READ_GRANT \
	(KACS_ACCESS_READ_CONTROL | KACS_ACCESS_ACCESS_SYSTEM_SECURITY)

#define PKM_KUNIT_PIP_TYPE_PROTECTED 512U

#define PKM_KUNIT_PIP_TYPE_ISOLATED 1024U

#define PKM_KUNIT_PIP_TRUST_TEST 5U

#define PKM_KUNIT_SE_CREATE_TOKEN_PRIVILEGE (1ULL << 2)

#define PKM_KUNIT_SE_ASSIGN_PRIMARY_PRIVILEGE (1ULL << 3)

#define PKM_KUNIT_SE_LOCK_MEMORY_PRIVILEGE (1ULL << 4)

#define PKM_KUNIT_SE_INCREASE_QUOTA_PRIVILEGE (1ULL << 5)

#define PKM_KUNIT_SE_TCB_PRIVILEGE (1ULL << 7)

#define PKM_KUNIT_SE_LOAD_DRIVER_PRIVILEGE (1ULL << 10)

#define PKM_KUNIT_SE_SYSTEMTIME_PRIVILEGE (1ULL << 12)

#define PKM_KUNIT_SE_PROFILE_SINGLE_PROCESS_PRIVILEGE (1ULL << 13)

#define PKM_KUNIT_SE_INCREASE_BASE_PRIORITY_PRIVILEGE (1ULL << 14)

#define PKM_KUNIT_SE_SHUTDOWN_PRIVILEGE (1ULL << 19)

#define PKM_KUNIT_SE_DEBUG_PRIVILEGE (1ULL << 20)

#define PKM_KUNIT_SE_CHANGE_NOTIFY_PRIVILEGE (1ULL << 23)

#define PKM_KUNIT_SE_REMOTE_SHUTDOWN_PRIVILEGE (1ULL << 24)

#define PKM_KUNIT_SE_SECURITY_PRIVILEGE (1ULL << 8)

#define PKM_KUNIT_SE_TAKE_OWNERSHIP_PRIVILEGE (1ULL << 9)

#define PKM_KUNIT_SE_RESTORE_PRIVILEGE (1ULL << 18)

#define PKM_KUNIT_SE_RELABEL_PRIVILEGE (1ULL << 32)

#define PKM_KUNIT_SE_AUDIT_PRIVILEGE (1ULL << 21)

#define PKM_KUNIT_SE_IMPERSONATE_PRIVILEGE (1ULL << 29)

#define PKM_KUNIT_SE_CREATE_SYMBOLIC_LINK_PRIVILEGE (1ULL << 35)

#define PKM_KUNIT_SE_BIND_PRIVILEGED_PORT_PRIVILEGE (1ULL << 63)

#define PKM_KUNIT_AUDIT_POLICY_OBJECT_ACCESS_SUCCESS 0x00000001U

#define PKM_KUNIT_SYSTEM_PRIVILEGES_ALL 0xC000000FFFFFFFFCULL

#define PKM_KUNIT_SE_PRIVILEGE_ENABLED 0x00000002U

#define PKM_KUNIT_SE_PRIVILEGE_REMOVED 0x00000004U

#define PKM_KUNIT_PRIV_RESET_ALL_DEFAULTS 0x80000000U

#define PKM_KUNIT_PRIV_LUID_SECURITY 8U

#define PKM_KUNIT_PRIV_LUID_AUDIT 21U

#define PKM_KUNIT_PRIV_LUID_REMOVE 2U

#define PKM_KUNIT_PRIV_LUID_ENABLE 5U

#define PKM_KUNIT_PRIV_LUID_DISABLE 9U

#define PKM_KUNIT_PRIV_LUID_ABSENT_DISABLE 12U

#define PKM_KUNIT_PRIV_LUID_ABSENT_REMOVE 13U

#define PKM_KUNIT_ADJUSTABLE_PRIV_PRESENT \
	((1ULL << PKM_KUNIT_PRIV_LUID_REMOVE) | \
	 (1ULL << PKM_KUNIT_PRIV_LUID_ENABLE) | \
	 (1ULL << PKM_KUNIT_PRIV_LUID_DISABLE))

#define PKM_KUNIT_ADJUSTABLE_PRIV_ENABLED \
	((1ULL << PKM_KUNIT_PRIV_LUID_REMOVE) | \
	 (1ULL << PKM_KUNIT_PRIV_LUID_DISABLE))

#define PKM_KUNIT_ADJUSTABLE_PRIV_ENABLED_BY_DEFAULT \
	PKM_KUNIT_ADJUSTABLE_PRIV_ENABLED

#define PKM_KUNIT_ADJUSTABLE_PRIV_AFTER_ENABLE_DISABLE \
	((1ULL << PKM_KUNIT_PRIV_LUID_REMOVE) | \
	 (1ULL << PKM_KUNIT_PRIV_LUID_ENABLE))

#define PKM_KUNIT_ADJUSTABLE_PRIV_AFTER_REMOVE \
	((1ULL << PKM_KUNIT_PRIV_LUID_ENABLE) | \
	 (1ULL << PKM_KUNIT_PRIV_LUID_DISABLE))

#define PKM_KUNIT_SE_GROUP_MANDATORY 0x00000001U

#define PKM_KUNIT_SE_GROUP_ENABLED_BY_DEFAULT 0x00000002U

#define PKM_KUNIT_SE_GROUP_ENABLED 0x00000004U

#define PKM_KUNIT_SE_GROUP_OWNER 0x00000008U

#define PKM_KUNIT_SE_GROUP_USE_FOR_DENY_ONLY 0x00000010U

#define PKM_KUNIT_SE_GROUP_RESOURCE 0x20000000U

#define PKM_KUNIT_SE_GROUP_LOGON_ID 0xC0000000U

#define PKM_KUNIT_DEFAULT_TOKEN_SELF_ACCESS \
	(KACS_TOKEN_QUERY | KACS_TOKEN_ADJUST_PRIVS | \
	 KACS_TOKEN_ADJUST_GROUPS | KACS_TOKEN_ADJUST_DEFAULT)

#define PKM_KUNIT_ADJUSTABLE_GROUP0_DEFAULT 0x0000000EU

#define PKM_KUNIT_ADJUSTABLE_GROUP1_DEFAULT 0x00000000U

#define PKM_KUNIT_ADJUSTABLE_GROUP2_DEFAULT 0x00000010U

#define PKM_KUNIT_ADJUSTABLE_GROUP3_DEFAULT 0x00000006U

#define PKM_KUNIT_ADJUSTABLE_GROUP4_DEFAULT 0xC0000007U

#define PKM_KUNIT_ADJUSTABLE_GROUP_PREV_MASK 0x19ULL

#define PKM_KUNIT_ADJUSTABLE_GROUP_MUTATED_MASK 0x1AULL

#define PKM_KUNIT_MAX_TOKEN_GROUPS KACS_TOKEN_MAX_GROUPS

#define PKM_KUNIT_MAX_CALLER_GROUPS (PKM_KUNIT_MAX_TOKEN_GROUPS - 1U)

/* Sized to hold a full MAX_TOKEN_GROUPS spec (~20 bytes/group) under the
 * 64 KiB MAX_TOKEN_SPEC_BYTES kernel limit. */
#define PKM_KUNIT_GROUP_LIMIT_TOKEN_SPEC_BYTES 49152U

#define PKM_KUNIT_KMES_PROCESS_NAME "kunit-ac"

#define PKM_KUNIT_KMES_PROCESS_PATH "/kunit/access-check"

#define PKM_KUNIT_KMES_PRIV_PROCESS_NAME "kunit-priv"

#define PKM_KUNIT_KMES_PRIV_PROCESS_PATH "/kunit/privilege"

#define PKM_KUNIT_KMES_DIRECT_TYPE "kunit-smoke"

#define PKM_KUNIT_KMES_USER_TYPE "kmes-user"

#define PKM_KUNIT_KMES_BATCH_TYPE0 "kmes-batch0"

#define PKM_KUNIT_KMES_BATCH_TYPE1 "kmes-batch1"

#define PKM_KUNIT_KMES_CAPTURE_BYTES 2048U

#define PKM_KUNIT_KMES_DEFAULT_CAPACITY (4U * 1024U * 1024U)

#define PKM_KUNIT_KMES_SWAP_CAPACITY (1U * 1024U * 1024U)

#define PKM_KUNIT_KMES_DOWNSIZE_CAPACITY (128U * 1024U)

#define PKM_KUNIT_KMES_DEFAULT_RATE 10000U

#define PKM_KUNIT_KMES_MIN_CAPACITY (64U * 1024U)

#define PKM_KUNIT_KMES_MAX_CAPACITY (256U * 1024U * 1024U)

#define PKM_KUNIT_KMES_MIN_EVENT_SIZE 1024U

#define PKM_KUNIT_KMES_MAX_EVENT_SIZE (4U * 1024U * 1024U)

#define PKM_KUNIT_KMES_MIN_NESTING_DEPTH 4U

#define PKM_KUNIT_KMES_MAX_NESTING_DEPTH 256U

#define PKM_KUNIT_KMES_MIN_RATE 100U

#define PKM_KUNIT_KMES_MAX_RATE 1000000U

#define PKM_KUNIT_USER_KIND_SYSTEM 0U

#define PKM_KUNIT_USER_KIND_LOCAL_SERVICE 1U

#define PKM_KUNIT_PRLIMIT_READ 1U

#define PKM_KUNIT_PRLIMIT_WRITE 2U

#define PKM_KUNIT_EXEC_SETID_UID 0x1U

#define PKM_KUNIT_EXEC_SETID_GID 0x2U

#define PKM_KUNIT_IL_UNTRUSTED 0U

#define PKM_KUNIT_IL_LOW 4096U

#define PKM_KUNIT_IL_MEDIUM 8192U

#define PKM_KUNIT_IL_HIGH 12288U

#define PKM_KUNIT_IL_SYSTEM 16384U

#define PKM_KUNIT_LOGON_TYPE_INTERACTIVE 2U

#define PKM_KUNIT_LOGON_TYPE_NETWORK 3U

#define PKM_KUNIT_LOGON_TYPE_BATCH 4U

#define PKM_KUNIT_LOGON_TYPE_SERVICE 5U

#define PKM_KUNIT_LOGON_TYPE_NETWORK_CLEARTEXT 8U

#define PKM_KUNIT_LOGON_TYPE_NEW_CREDENTIALS 9U

#define PKM_KUNIT_CLAIM_TYPE_INT64 0x0001U

#define PKM_KUNIT_CLAIM_TYPE_UINT64 0x0002U

#define PKM_KUNIT_CLAIM_TYPE_STRING 0x0003U

#define PKM_KUNIT_CLAIM_TYPE_SID 0x0005U

#define PKM_KUNIT_CLAIM_TYPE_BOOLEAN 0x0006U

#define PKM_KUNIT_CLAIM_TYPE_OCTET 0x0010U

#define PKM_KUNIT_CLAIM_DISABLED 0x00000010U

#define PKM_KUNIT_COND_USER_CLAIM 0xf9U

#define PKM_KUNIT_COND_RESOURCE_CLAIM 0xfaU

#define PKM_KUNIT_COND_DEVICE_CLAIM 0xfbU

#define PKM_KUNIT_OWNER_SECURITY_INFORMATION 0x00000001U

#define PKM_KUNIT_GROUP_SECURITY_INFORMATION 0x00000002U

#define PKM_KUNIT_DACL_SECURITY_INFORMATION 0x00000004U

#define PKM_KUNIT_SACL_SECURITY_INFORMATION 0x00000008U

#define PKM_KUNIT_LABEL_SECURITY_INFORMATION 0x00000010U

#define PKM_KUNIT_OBJECT_INHERIT_ACE 0x01U

#define PKM_KUNIT_CONTAINER_INHERIT_ACE 0x02U

#define PKM_KUNIT_NO_PROPAGATE_INHERIT_ACE 0x04U

#define PKM_KUNIT_INHERIT_ONLY_ACE 0x08U

#define PKM_KUNIT_INHERITED_ACE 0x10U

#define PKM_KUNIT_OPAQUE_ACE_TYPE 0x7fU

#define PKM_KUNIT_SE_OWNER_DEFAULTED 0x0001U

#define PKM_KUNIT_SE_GROUP_DEFAULTED 0x0002U

#define PKM_KUNIT_SE_DACL_PRESENT 0x0004U

#define PKM_KUNIT_SE_DACL_DEFAULTED 0x0008U

#define PKM_KUNIT_SE_SACL_PRESENT 0x0010U

#define PKM_KUNIT_SE_SACL_DEFAULTED 0x0020U

#define PKM_KUNIT_SE_DACL_TRUSTED 0x0040U

#define PKM_KUNIT_SE_SERVER_SECURITY 0x0080U

#define PKM_KUNIT_SE_DACL_AUTO_INHERIT_REQ 0x0100U

#define PKM_KUNIT_SE_SACL_AUTO_INHERIT_REQ 0x0200U

#define PKM_KUNIT_SE_DACL_AUTO_INHERITED 0x0400U

#define PKM_KUNIT_SE_SACL_AUTO_INHERITED 0x0800U

#define PKM_KUNIT_SE_DACL_PROTECTED 0x1000U

#define PKM_KUNIT_SE_SACL_PROTECTED 0x2000U

#define PKM_KUNIT_SE_RM_CONTROL_VALID 0x4000U

#define PKM_KUNIT_SE_SELF_RELATIVE 0x8000U

#define PKM_KUNIT_ACCESS_ALLOWED_ACE_TYPE 0x00U

#define PKM_KUNIT_ACCESS_DENIED_ACE_TYPE 0x01U

#define PKM_KUNIT_MAX_SECURITY_DESCRIPTOR_BYTES 65535U

#define PKM_KUNIT_TOKEN_INDEX_NO_CHANGE 0xFFFFFFFFU

#define PKM_KUNIT_TOKEN_SPEC_VERSION 2U

#define PKM_KUNIT_TOKEN_SPEC_HEADER_LEN 192U

#define PKM_KUNIT_FILE_READ_DATA 0x00000001U

#define PKM_KUNIT_FILE_WRITE_DATA 0x00000002U

#define PKM_KUNIT_FILE_APPEND_DATA 0x00000004U

#define PKM_KUNIT_FILE_LIST_DIRECTORY PKM_KUNIT_FILE_READ_DATA

#define PKM_KUNIT_FILE_READ_EA 0x00000008U

#define PKM_KUNIT_FILE_WRITE_EA 0x00000010U

#define PKM_KUNIT_FILE_EXECUTE 0x00000020U

#define PKM_KUNIT_FILE_TRAVERSE PKM_KUNIT_FILE_EXECUTE

#define PKM_KUNIT_FILE_ADD_FILE PKM_KUNIT_FILE_WRITE_DATA

#define PKM_KUNIT_FILE_ADD_SUBDIRECTORY PKM_KUNIT_FILE_APPEND_DATA

#define PKM_KUNIT_FILE_DELETE_CHILD 0x00000040U

#define PKM_KUNIT_FILE_READ_ATTRIBUTES 0x00000080U

#define PKM_KUNIT_FILE_WRITE_ATTRIBUTES 0x00000100U

#define PKM_KUNIT_FILE_SD_ADMIN_MASK                                           \
	(PKM_KUNIT_FILE_READ_DATA | PKM_KUNIT_FILE_WRITE_DATA |               \
	 PKM_KUNIT_FILE_APPEND_DATA | PKM_KUNIT_FILE_READ_EA |               \
	 PKM_KUNIT_FILE_WRITE_EA | PKM_KUNIT_FILE_EXECUTE |                 \
	 PKM_KUNIT_FILE_DELETE_CHILD | PKM_KUNIT_FILE_READ_ATTRIBUTES |      \
	 PKM_KUNIT_FILE_WRITE_ATTRIBUTES | KACS_ACCESS_DELETE |              \
	 KACS_ACCESS_READ_CONTROL | KACS_ACCESS_WRITE_DAC |                  \
	 KACS_ACCESS_WRITE_OWNER)

#define PKM_KUNIT_FILE_SD_QUERY_MASK KACS_ACCESS_READ_CONTROL

#define PKM_KUNIT_FILE_SD_WRITE_MASK KACS_ACCESS_WRITE_DAC

#define PKM_KUNIT_FILE_SD_SACL_MASK KACS_ACCESS_ACCESS_SYSTEM_SECURITY


#ifndef PTRACE_MODE_GETFD

#define PTRACE_MODE_GETFD 0x20

#endif


#ifndef ARCH_SHSTK_DISABLE

#define ARCH_SHSTK_DISABLE 0x5002

#endif


extern size_t kacs_rust_kunit_probe(void);


#define PKM_KUNIT_ASSERT_SIZE(type, expected) \
	static_assert(sizeof(type) == (expected))

#define PKM_KUNIT_ASSERT_OFFSET(type, member, expected) \
	static_assert(offsetof(type, member) == (expected))

#define PKM_KUNIT_ASSERT_IOC(cmd, nr, dir, arg_size) \
	static_assert(_IOC_TYPE(cmd) == KACS_IOC_MAGIC); \
	static_assert(_IOC_NR(cmd) == (nr)); \
	static_assert(_IOC_DIR(cmd) == (dir)); \
	static_assert(_IOC_SIZE(cmd) == (arg_size))


void pkm_kunit_expect_bytes_eq(struct kunit *test, const u8 *actual,
				      size_t actual_len, const u8 *expected,
				      size_t expected_len);


struct pkm_kunit_region {
	u64 base;
	u8 *bytes;
	size_t len;
	bool fault_read;
	bool fault_write;
};


struct pkm_kunit_mem {
	struct pkm_kunit_region regions[8];
	size_t count;
};


struct pkm_kunit_event_counts {
	u32 audit_events;
	u32 privilege_use_events;
};


struct pkm_kunit_linked_pair {
	const void *source_token;
	long elevated_fd;
	long filtered_fd;
	u64 session_id;
};


struct pkm_kunit_sid_attr_spec {
	const u8 *sid;
	size_t sid_len;
	u32 attributes;
};


struct pkm_kunit_token_spec_args {
	u8 token_type;
	u8 impersonation_level;
	u32 integrity_level;
	u32 mandatory_policy;
	u64 privileges_present;
	u64 privileges_enabled;
	u32 projected_uid;
	u32 projected_gid;
	u32 allow_zero_projected_uid;
	u32 allow_zero_projected_gid;
	u32 audit_policy;
	u64 expiration;
	u64 session_id;
	u32 owner_sid_index;
	u32 primary_group_index;
	const u8 *source_name;
	u64 source_id;
	const u8 *user_sid;
	size_t user_sid_len;
	const struct pkm_kunit_sid_attr_spec *groups;
	u32 group_count;
	const u8 *default_dacl;
	size_t default_dacl_len;
	const u8 *user_claims;
	size_t user_claims_len;
	const u8 *device_claims;
	size_t device_claims_len;
	const struct pkm_kunit_sid_attr_spec *device_groups;
	u32 device_group_count;
	const struct pkm_kunit_sid_attr_spec *restricted_sids;
	u32 restricted_sid_count;
	const u8 *confinement_sid;
	size_t confinement_sid_len;
	const struct pkm_kunit_sid_attr_spec *confinement_caps;
	u32 confinement_cap_count;
	u32 confinement_exempt;
	u32 write_restricted;
	u32 user_deny_only;
	u32 isolation_boundary;
	const u32 *projected_supplementary_gids;
	u32 projected_supplementary_gid_count;
	const struct pkm_kunit_sid_attr_spec *restricted_device_groups;
	u32 restricted_device_group_count;
	u64 origin;
	u32 interactive_session_id;
};


struct pkm_kunit_kmes_event_view {
	u32 event_size;
	u32 header_size;
	u64 timestamp;
	u64 sequence;
	u16 cpu_id;
	u8 origin_class;
	const u8 *effective_token_guid;
	const u8 *true_token_guid;
	const u8 *process_guid;
	u16 type_len;
	const u8 *type_ptr;
	const u8 *payload_ptr;
	size_t payload_len;
};


size_t pkm_kunit_build_session_spec(u8 *dst, u8 logon_type,
					   const char *auth_pkg,
					   const u8 *user_sid,
					   size_t user_sid_len);

size_t pkm_kunit_build_token_spec(
	u8 *dst, size_t dst_len, const struct pkm_kunit_token_spec_args *args);


enum pkm_kunit_msgpack_kind {
	PKM_KUNIT_MSGPACK_NIL = 0,
	PKM_KUNIT_MSGPACK_BOOL,
	PKM_KUNIT_MSGPACK_UINT,
	PKM_KUNIT_MSGPACK_STR,
	PKM_KUNIT_MSGPACK_BIN,
	PKM_KUNIT_MSGPACK_ARRAY,
	PKM_KUNIT_MSGPACK_MAP,
};


struct pkm_kunit_msgpack_view {
	enum pkm_kunit_msgpack_kind kind;
	const u8 *data_ptr;
	size_t data_len;
	size_t total_len;
	u32 count;
	u64 uint_value;
	bool bool_value;
};


struct pkm_kunit_read_ace_spec {
	u8 ace_type;
	const u8 *sid;
	size_t sid_len;
};


#define PKM_KUNIT_SIGNING_BLOB_LEN 65U

#define PKM_KUNIT_SIGNING_SIG_LEN 64U

#define PKM_KUNIT_SIGNING_VERSION 0x01U

#define PKM_KUNIT_ELF_LEN 512U

#define PKM_KUNIT_ELF_SIG_OFFSET 0x40U

#define PKM_KUNIT_ELF_STRTAB_OFFSET 0x90U

#define PKM_KUNIT_ELF_SHOFF 0x100U

#define PKM_KUNIT_SIGNING_PIP_PROTECTED 512U

#define PKM_KUNIT_SIGNING_TRUST_TCB 8192U


struct pkm_kunit_continuous_audit_op_case {
	u32 op;
	const char *operation;
	u32 granted;
	u32 continuous_audit;
	int file_flags;
	unsigned long arg0;
	unsigned long arg1;
	u32 requested;
	u32 matched;
	bool success;
	int expected_ret;
};


const u8 *pkm_kunit_create_precise_file_sd(const void *token,
						  u32 self_mask,
						  size_t *len_out);

void pkm_kunit_make_first_file_ace_inheritable(u8 *sd_bytes,
						      u8 inherit_flags);


struct pkm_kunit_ioctl_expectation {
	unsigned int cmd;
	umode_t mode;
	u32 allowed_access;
	u32 denied_access;
	bool compat;
};


struct pkm_kunit_inheritance_flags_case {
	u8 parent_flags;
	bool file_inherits;
	u8 file_flags;
	bool dir_inherits;
	u8 dir_flags;
};


struct pkm_kunit_impersonation_gate_case {
	u32 server_user_kind;
	u32 client_user_kind;
	u32 server_integrity;
	u32 client_integrity;
	u32 server_restricted;
	u32 client_restricted;
	u64 server_privileges_present;
	u64 server_privileges_enabled;
	u64 server_privileges_enabled_by_default;
	u32 requested_level;
	u32 expected_level;
	u32 expected_used_impersonate;
};


/* Shared const test data (small; duplicated per TU is fine). */

static __maybe_unused const u8 pkm_kunit_kmes_ring_magic[] = "KMESRING";

static __maybe_unused const u8 pkm_kunit_anonymous_sid[] = {
	1, 1, 0, 0, 0, 0, 0, 5, 7, 0, 0, 0
};

static __maybe_unused const u8 pkm_kunit_local_service_sid[] = {
	1, 1, 0, 0, 0, 0, 0, 5, 19, 0, 0, 0
};

static __maybe_unused const u8 pkm_kunit_system_sid[] = {
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0
};

static __maybe_unused const u8 pkm_kunit_administrators_sid[] = {
	1, 2, 0, 0, 0, 0, 0, 5, 32, 0, 0, 0, 32, 2, 0, 0
};

static __maybe_unused const u8 pkm_kunit_owner_rights_sid[] = {
	1, 1, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0
};

static __maybe_unused const u8 pkm_kunit_creator_owner_sid[] = {
	1, 1, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0
};

static __maybe_unused const u8 pkm_kunit_creator_group_sid[] = {
	1, 1, 0, 0, 0, 0, 0, 3, 1, 0, 0, 0
};

static __maybe_unused const u8 pkm_kunit_everyone_sid[] = {
	1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0
};

static __maybe_unused const u8 pkm_kunit_authenticated_users_sid[] = {
	1, 1, 0, 0, 0, 0, 0, 5, 11, 0, 0, 0
};

static __maybe_unused const u8 pkm_kunit_all_restricted_application_packages_sid[] = {
	1, 2, 0, 0, 0, 0, 0, 15, 2, 0, 0, 0, 2, 0, 0, 0
};

static __maybe_unused const u8 pkm_kunit_sample_confinement_sid[] = {
	1, 2, 0, 0, 0, 0, 0, 15, 2, 0, 0, 0, 0xe8, 0x03, 0, 0
};


static __maybe_unused const u8 pkm_kunit_system_read_sd[] = {
	1, 0, 4, 128, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	32, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	2, 0, 28, 0, 1, 0, 0, 0,
	0, 0, 20, 0, 0, 0, 2, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
};


static __maybe_unused const u8 pkm_kunit_everyone_read_sd[] = {
	1, 0, 4, 128, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	32, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	2, 0, 28, 0, 1, 0, 0, 0,
	0, 0, 20, 0, 0, 0, 2, 0,
	1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
};


static __maybe_unused const u8 pkm_kunit_anonymous_read_sd[] = {
	1, 0, 4, 128, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	32, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	2, 0, 28, 0, 1, 0, 0, 0,
	0, 0, 20, 0, 0, 0, 2, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 7, 0, 0, 0,
};


static __maybe_unused const u8 pkm_kunit_authenticated_users_read_sd[] = {
	1, 0, 4, 128, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	32, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	2, 0, 28, 0, 1, 0, 0, 0,
	0, 0, 20, 0, 0, 0, 2, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 11, 0, 0, 0,
};


static __maybe_unused const u8 pkm_kunit_system_default_dacl[] = {
	2, 0, 52, 0, 2, 0, 0, 0,
	0, 0, 20, 0, 0, 0, 0, 16,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	0, 0, 24, 0, 0, 0, 0, 16,
	1, 2, 0, 0, 0, 0, 0, 5, 32, 0, 0, 0, 32, 2, 0, 0,
};


static __maybe_unused const u8 pkm_kunit_replacement_default_dacl[] = {
	2, 0, 28, 0, 1, 0, 0, 0,
	0, 0, 20, 0, 0, 0, 0, 16,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
};


static __maybe_unused const u8 pkm_kunit_invalid_default_dacl[] = {
	2, 0, 7, 0, 0, 0, 0, 0,
};


/* Owner SYSTEM, success-audit SYSTEM READ_CONTROL, allow SYSTEM READ_CONTROL. */
static __maybe_unused const u8 pkm_kunit_system_read_audit_sd[] = {
	1, 0, 20, 128, 20, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0,
	60, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	2, 0, 28, 0, 1, 0, 0, 0,
	2, 64, 20, 0, 0, 0, 2, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	2, 0, 28, 0, 1, 0, 0, 0,
	0, 0, 20, 0, 0, 0, 2, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
};


/* Owner SYSTEM, alarm SYSTEM FILE_READ_DATA, allow SYSTEM read-open subset. */
static __maybe_unused const u8 pkm_kunit_system_file_read_alarm_sd[] = {
	1, 0, 20, 128, 20, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0,
	60, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	2, 0, 28, 0, 1, 0, 0, 0,
	3, 0, 20, 0, 1, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	2, 0, 28, 0, 1, 0, 0, 0,
	0, 0, 20, 0, 137, 0, 6, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
};


/* Owner SYSTEM, audit SYSTEM FILE_READ_DATA, allow SYSTEM read-open subset. */
static __maybe_unused const u8 pkm_kunit_system_file_read_audit_sd[] = {
	1, 0, 20, 128, 20, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0,
	60, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	2, 0, 28, 0, 1, 0, 0, 0,
	2, 192, 20, 0, 1, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	2, 0, 28, 0, 1, 0, 0, 0,
	0, 0, 20, 0, 137, 0, 6, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
};


/* Owner SYSTEM, success-audit SYSTEM ACCESS_SYSTEM_SECURITY. */
static __maybe_unused const u8 pkm_kunit_system_set_sd_audit_sd[] = {
	1, 0, 20, 128, 20, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0,
	60, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	2, 0, 28, 0, 1, 0, 0, 0,
	2, 64, 20, 0, 0, 0, 0, 1,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	2, 0, 28, 0, 1, 0, 0, 0,
	0, 0, 20, 0, 0, 0, 2, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
};


static __maybe_unused const u8 pkm_kunit_system_pip_sd[] = {
	1, 0, 20, 128, 20, 0, 0, 0, 32, 0, 0, 0, 44, 0, 0, 0,
	76, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	4, 0, 32, 0, 1, 0, 0, 0,
	20, 0, 24, 0, 0, 0, 2, 0,
	1, 2, 0, 0, 0, 0, 0, 19, 0, 2, 0, 0, 5, 0, 0, 0,
	4, 0, 28, 0, 1, 0, 0, 0,
	0, 0, 20, 0, 0, 0, 6, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
};


static __maybe_unused const u8 pkm_kunit_everyone_pip_sd[] = {
	1, 0, 20, 128, 20, 0, 0, 0, 32, 0, 0, 0, 44, 0, 0, 0,
	76, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	4, 0, 32, 0, 1, 0, 0, 0,
	20, 0, 24, 0, 0, 0, 2, 0,
	1, 2, 0, 0, 0, 0, 0, 19, 0, 2, 0, 0, 5, 0, 0, 0,
	4, 0, 28, 0, 1, 0, 0, 0,
	0, 0, 20, 0, 0, 0, 6, 0,
	1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
};


static __maybe_unused const u8 pkm_kunit_everyone_file_read_pip_sd[] = {
	1, 0, 20, 128, 20, 0, 0, 0, 32, 0, 0, 0, 44, 0, 0, 0,
	76, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	4, 0, 32, 0, 1, 0, 0, 0,
	20, 0, 24, 0, 0, 0, 2, 0,
	1, 2, 0, 0, 0, 0, 0, 19, 0, 2, 0, 0, 5, 0, 0, 0,
	4, 0, 28, 0, 1, 0, 0, 0,
	0, 0, 20, 0, 137, 0, 6, 0,
	1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
};


static __maybe_unused const u8 pkm_kunit_everyone_process_query_pip_sd[] = {
	1, 0, 20, 128, 20, 0, 0, 0, 32, 0, 0, 0, 44, 0, 0, 0,
	76, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	4, 0, 32, 0, 1, 0, 0, 0,
	20, 0, 24, 0, 0, 0, 2, 0,
	1, 2, 0, 0, 0, 0, 0, 19, 0, 2, 0, 0, 5, 0, 0, 0,
	4, 0, 28, 0, 1, 0, 0, 0,
	0, 0, 20, 0, 0, 16, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
};


static __maybe_unused const u8 pkm_kunit_caap_policy_sid[] = {
	1, 2, 0, 0, 0, 0, 0, 5, 21, 0, 0, 0, 4, 1, 0, 0,
};


static __maybe_unused const u8 pkm_kunit_caap_object_sd[] = {
	1, 0, 20, 128, 20, 0, 0, 0, 36, 0, 0, 0, 48, 0, 0, 0,
	80, 0, 0, 0,
	1, 2, 0, 0, 0, 0, 0, 5, 21, 0, 0, 0, 231, 3, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	4, 0, 32, 0, 1, 0, 0, 0,
	19, 0, 24, 0, 0, 0, 0, 0,
	1, 2, 0, 0, 0, 0, 0, 5, 21, 0, 0, 0, 4, 1, 0, 0,
	4, 0, 28, 0, 1, 0, 0, 0,
	0, 0, 20, 0, 0, 0, 2, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
};


static __maybe_unused const u8 pkm_kunit_caap_empty_dacl[] = {
	4, 0, 8, 0, 0, 0, 0, 0,
};


static __maybe_unused const u8 pkm_kunit_caap_system_read_dacl[] = {
	4, 0, 28, 0, 1, 0, 0, 0,
	0, 0, 20, 0, 0, 0, 2, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
};


static __maybe_unused const u8 pkm_kunit_caap_file_read_dacl[] = {
	4, 0, 28, 0, 1, 0, 0, 0,
	0, 0, 20, 0,
	PKM_KUNIT_FILE_READ_DATA | PKM_KUNIT_FILE_READ_ATTRIBUTES, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
};


static __maybe_unused const u8 pkm_kunit_caap_file_read_sd[] = {
	1, 0, 20, 128, 20, 0, 0, 0, 32, 0, 0, 0, 44, 0, 0, 0,
	76, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
	4, 0, 32, 0, 1, 0, 0, 0,
	19, 0, 24, 0, 0, 0, 0, 0,
	1, 2, 0, 0, 0, 0, 0, 5, 21, 0, 0, 0, 4, 1, 0, 0,
	4, 0, 28, 0, 1, 0, 0, 0,
	0, 0, 20, 0,
	PKM_KUNIT_FILE_READ_DATA | PKM_KUNIT_FILE_READ_ATTRIBUTES, 0, 0, 0,
	1, 1, 0, 0, 0, 0, 0, 5, 18, 0, 0, 0,
};


static __maybe_unused const struct file_operations pkm_kunit_file_fd_transfer_fops = { };


static __maybe_unused const struct file_operations pkm_kunit_non_process_fops = { };


static __maybe_unused const struct file_operations pkm_kunit_non_token_fops = { };


/* Helper prototypes (definitions in kunit_common.c). */

bool pkm_kunit_mem_read(void *ctx, u64 user_ptr, void *dst, size_t len);

bool pkm_kunit_mem_write(void *ctx, u64 user_ptr, const void *src, size_t len);

bool pkm_kunit_on_audit_event(void *ctx,
				     const struct pkm_kacs_audit_event_view *event);

bool pkm_kunit_on_privilege_use_event(
	void *ctx, const struct pkm_kacs_privilege_use_event_view *event);

bool pkm_kunit_fail_audit_event(
	void *ctx, const struct pkm_kacs_audit_event_view *event);

void pkm_kunit_add_region(struct pkm_kunit_mem *mem, u64 base, u8 *bytes,
				 size_t len);

void pkm_kunit_write_u32(u8 *bytes, size_t offset, u32 value);

void pkm_kunit_write_u64(u8 *bytes, size_t offset, u64 value);

void pkm_kunit_write_u16(u8 *bytes, size_t offset, u16 value);

size_t pkm_kunit_utf16_cstr_len(const char *value);

void pkm_kunit_write_utf16_cstr(u8 *bytes, size_t offset,
				       const char *value);

size_t pkm_kunit_build_claim_entry_empty(u8 *dst, size_t dst_len,
						const char *name, u16 value_type,
						u32 flags);

size_t pkm_kunit_build_claim_entry_scalar(u8 *dst, size_t dst_len,
						 const char *name, u16 value_type,
						 u32 flags, u64 value);

size_t pkm_kunit_build_claim_entry_string(u8 *dst, size_t dst_len,
						 const char *name, u32 flags,
						 const char *value);

size_t pkm_kunit_build_claim_entry_sid(u8 *dst, size_t dst_len,
					      const char *name, u32 flags,
					      const u8 *sid, size_t sid_len);

size_t pkm_kunit_build_claim_entry_octet(u8 *dst, size_t dst_len,
						const char *name, u32 flags,
						const u8 *value, size_t value_len);

int pkm_kunit_append_claim_entry(u8 *dst, size_t dst_len,
					size_t *offset_io, const u8 *entry,
					size_t entry_len);

u32 pkm_kunit_read_u32(const u8 *bytes, size_t offset);

u16 pkm_kunit_read_u16(const u8 *bytes, size_t offset);

void pkm_kunit_make_sd_ownerless(u8 *sd);

void pkm_kunit_make_sd_groupless(u8 *sd);

size_t pkm_kunit_build_owner_subset_sd(u8 *dst, size_t dst_len,
					      const u8 *owner_sid,
					      size_t owner_sid_len);

void pkm_kunit_set_sd_rm_control(u8 *sd, u8 value);

void pkm_kunit_expect_sd_rm_control(struct kunit *test, const u8 *sd,
					   u8 value);

void pkm_kunit_set_sd_dacl_reserved_fields(u8 *sd, u8 sbz1, u16 sbz2);

void pkm_kunit_expect_sd_dacl_reserved_fields(struct kunit *test,
						     const u8 *sd, u8 sbz1,
						     u16 sbz2);

void pkm_kunit_expect_sd_sid_component(struct kunit *test, const u8 *sd,
					      size_t sd_len, size_t offset,
					      const u8 *expected_sid,
					      size_t expected_sid_len);

void pkm_kunit_expect_stored_sd_has_owner(struct kunit *test,
						 const u8 *sd, size_t sd_len);

const u8 *pkm_kunit_dacl_ace_const(const u8 *sd, size_t sd_len,
					  u16 target_index);

u8 *pkm_kunit_dacl_ace(u8 *sd, size_t sd_len, u16 target_index);

void pkm_kunit_set_dacl_ace_header(u8 *sd, size_t sd_len,
					  u16 index, u8 ace_type,
					  u8 ace_flags, u32 mask);

void pkm_kunit_set_dacl_ace_sid(struct kunit *test, u8 *sd,
				       size_t sd_len, u16 index,
				       const u8 *sid, size_t sid_len);

void pkm_kunit_expect_dacl_ace_header(struct kunit *test, const u8 *sd,
					     size_t sd_len, u16 index,
					     u8 ace_type, u8 ace_flags,
					     u32 mask);

void pkm_kunit_expect_allow_ace(struct kunit *test, const u8 *sd,
				       size_t sd_len, u16 index, u32 mask,
				       const u8 *sid, size_t sid_len);

void pkm_kunit_expect_owner_rights_read_control_ace(
	struct kunit *test, const u8 *sd, size_t sd_len, u16 index);

u64 pkm_kunit_read_u64(const u8 *bytes, size_t offset);

u32 pkm_kunit_query_token_u32(struct kunit *test, int fd, u32 token_class);

u32 pkm_kunit_groups_query_attr(const u8 *bytes, u32 index);

void pkm_kunit_expect_bytes_eq(struct kunit *test, const u8 *actual,
				      size_t actual_len, const u8 *expected,
				      size_t expected_len);

void pkm_kunit_expect_token_query_payload_eq(struct kunit *test,
						    int lhs_fd, int rhs_fd,
						    u32 token_class);

bool pkm_kunit_snapshot_has_group(
	const struct pkm_kacs_boot_snapshot *snapshot,
	const u8 *sid, size_t sid_len, u32 *attributes_out);

void pkm_kunit_fill_group_limit_specs(
	struct pkm_kunit_sid_attr_spec *groups, u32 count);

bool pkm_kunit_contains_bytes(const u8 *haystack, size_t haystack_len,
				     const u8 *needle, size_t needle_len);

void pkm_kunit_reset_kmes(void);

void pkm_kunit_close_fds(struct kunit *test, int *fds, int count);

int pkm_kunit_dup_fd_same_file(int fd);

void pkm_kunit_cleanup_linked_pair(struct kunit *test,
					  struct pkm_kunit_linked_pair *pair);

int pkm_kunit_create_link_candidates(struct kunit *test,
					    const void *caller_token,
					    struct pkm_kunit_linked_pair *out);

int pkm_kunit_create_linked_pair(struct kunit *test,
					const void *caller_token,
					struct pkm_kunit_linked_pair *out);

int pkm_kunit_create_dynamic_linked_pair(struct kunit *test,
						const void *caller_token,
						struct pkm_kunit_linked_pair *out);

int pkm_kunit_find_current_kmes_fd(struct kunit *test, int *fds, int count,
					  struct pkm_kmes_kunit_fd_snapshot *out);
long pkm_kunit_kmes_attach_all(const void *token, int *fds, int *count,
				      u64 *capacity);

bool pkm_kunit_parse_kmes_event(
	const u8 *bytes, size_t len, struct pkm_kunit_kmes_event_view *out);

bool pkm_kunit_msgpack_read_be(const u8 *bytes, size_t len,
				      size_t width, u64 *out);

bool pkm_kunit_msgpack_parse_one(const u8 *bytes, size_t len,
					struct pkm_kunit_msgpack_view *out,
					u32 depth);

bool pkm_kunit_msgpack_map_get(const struct pkm_kunit_msgpack_view *map,
				      const char *key,
				      struct pkm_kunit_msgpack_view *out);

bool pkm_kunit_msgpack_str_eq(
	const struct pkm_kunit_msgpack_view *view, const char *expected);

bool pkm_kunit_msgpack_bin_eq(
	const struct pkm_kunit_msgpack_view *view, const u8 *expected,
	size_t expected_len);

bool pkm_kunit_msgpack_require_key(
	struct kunit *test, const struct pkm_kunit_msgpack_view *map,
	const char *key, enum pkm_kunit_msgpack_kind kind,
	struct pkm_kunit_msgpack_view *out);

bool pkm_kunit_msgpack_expect_uint_key(
	struct kunit *test, const struct pkm_kunit_msgpack_view *map,
	const char *key, u64 expected);

bool pkm_kunit_msgpack_expect_bool_key(
	struct kunit *test, const struct pkm_kunit_msgpack_view *map,
	const char *key, bool expected);

bool pkm_kunit_msgpack_expect_str_key(
	struct kunit *test, const struct pkm_kunit_msgpack_view *map,
	const char *key, const char *expected);

bool pkm_kunit_msgpack_expect_bin_key(
	struct kunit *test, const struct pkm_kunit_msgpack_view *map,
	const char *key, const u8 *expected, size_t expected_len);

bool pkm_kunit_msgpack_expect_nil_key(
	struct kunit *test, const struct pkm_kunit_msgpack_view *map,
	const char *key);

bool pkm_kunit_msgpack_expect_process_map(
	struct kunit *test, const struct pkm_kunit_msgpack_view *map,
	u64 expected_pid, const char *expected_name, const char *expected_path);

bool pkm_kunit_msgpack_expect_subject_map(
	struct kunit *test, const struct pkm_kunit_msgpack_view *map,
	const u8 *expected_user_sid, size_t expected_user_sid_len,
	u32 expected_integrity, u32 expected_pip_type, u32 expected_pip_trust);

bool pkm_kunit_msgpack_expect_subject_group_sids(
	struct kunit *test, const struct pkm_kunit_msgpack_view *map,
	const struct pkm_kunit_sid_attr_spec *expected_groups,
	u32 expected_group_count);

bool pkm_kunit_msgpack_parse_payload_root(
	struct kunit *test, const struct pkm_kunit_kmes_event_view *event,
	struct pkm_kunit_msgpack_view *root, u32 expected_count);

bool pkm_kunit_expect_kmes_event_type(
	struct kunit *test, const struct pkm_kunit_kmes_event_view *event,
	const char *expected);

bool pkm_kunit_expect_access_audit_schema(
	struct kunit *test, const struct pkm_kunit_kmes_event_view *event,
	u32 expected_requested, u32 expected_granted, bool expected_success,
	const char *expected_trigger_kind, const u8 *expected_ace,
	size_t expected_ace_len);

bool pkm_kunit_expect_access_audit_subject_group_sids(
	struct kunit *test, const struct pkm_kunit_kmes_event_view *event,
	const struct pkm_kunit_sid_attr_spec *expected_groups,
	u32 expected_group_count);

bool pkm_kunit_expect_access_audit_object_context(
	struct kunit *test, const struct pkm_kunit_kmes_event_view *event,
	const u8 *expected_context, size_t expected_context_len);

bool pkm_kunit_expect_continuous_audit_schema(
	struct kunit *test, const struct pkm_kunit_kmes_event_view *event,
	u32 expected_requested, u32 expected_matched, u32 expected_granted,
	bool expected_success);

bool pkm_kunit_expect_continuous_audit_schema_op(
	struct kunit *test, const struct pkm_kunit_kmes_event_view *event,
	const char *expected_operation, u32 expected_requested,
	u32 expected_matched, u32 expected_granted, bool expected_success,
	u32 expected_pip_type, u32 expected_pip_trust, u64 expected_pid);

bool pkm_kunit_expect_privilege_use_schema(
	struct kunit *test, const struct pkm_kunit_kmes_event_view *event,
	u32 expected_requested, u32 expected_granted, u32 expected_surviving,
	bool expected_success);

bool pkm_kunit_expect_caap_diagnostic_schema(
	struct kunit *test, const struct pkm_kunit_kmes_event_view *event,
	u32 expected_effective, u32 expected_staged);

bool pkm_kunit_expect_logon_destroyed_schema(
	struct kunit *test, const struct pkm_kunit_kmes_event_view *event,
	u64 expected_session_id, u32 expected_logon_type,
	const char *expected_auth_package, u64 expected_created_at);

void pkm_kunit_expect_boot_snapshot_eq_internal(
	struct kunit *test, const struct pkm_kacs_boot_snapshot *lhs,
	const struct pkm_kacs_boot_snapshot *rhs, bool compare_identity);

void pkm_kunit_expect_boot_snapshot_eq(
	struct kunit *test, const struct pkm_kacs_boot_snapshot *lhs,
	const struct pkm_kacs_boot_snapshot *rhs);

void pkm_kunit_expect_boot_snapshot_eq_except_identity(
	struct kunit *test, const struct pkm_kacs_boot_snapshot *lhs,
	const struct pkm_kacs_boot_snapshot *rhs);

void pkm_kunit_expect_boot_snapshot_scalars_eq_internal(
	struct kunit *test, const struct pkm_kacs_boot_snapshot *lhs,
	const struct pkm_kacs_boot_snapshot *rhs, bool compare_identity);

void pkm_kunit_expect_boot_snapshot_scalars_eq(
	struct kunit *test, const struct pkm_kacs_boot_snapshot *lhs,
	const struct pkm_kacs_boot_snapshot *rhs);

void pkm_kunit_expect_boot_snapshot_scalars_eq_except_identity(
	struct kunit *test, const struct pkm_kacs_boot_snapshot *lhs,
	const struct pkm_kacs_boot_snapshot *rhs);

bool pkm_kunit_guid_is_zero(const u8 guid[KACS_UUID_BYTES]);

bool pkm_kunit_guid_is_uuid_v4(const u8 guid[KACS_UUID_BYTES]);

void pkm_kunit_expect_guid_v4(struct kunit *test,
				     const u8 guid[KACS_UUID_BYTES]);

void pkm_kunit_expect_guid_eq(struct kunit *test,
				     const u8 lhs[KACS_UUID_BYTES],
				     const u8 rhs[KACS_UUID_BYTES]);

void pkm_kunit_expect_guid_ne(struct kunit *test,
				     const u8 lhs[KACS_UUID_BYTES],
				     const u8 rhs[KACS_UUID_BYTES]);

size_t pkm_kunit_build_session_spec(u8 *dst, u8 logon_type,
					   const char *auth_pkg,
					   const u8 *user_sid,
					   size_t user_sid_len);

size_t pkm_kunit_sid_attr_array_len(
	const struct pkm_kunit_sid_attr_spec *entries, u32 count);

size_t pkm_kunit_write_sid_attr_array(
	u8 *dst, const struct pkm_kunit_sid_attr_spec *entries, u32 count);

int pkm_kunit_append_bytes_section(u8 *dst, size_t dst_len,
					  size_t *offset_io,
					  const void *bytes, size_t len,
					  u32 *offset_out);

int pkm_kunit_append_sid_attr_section(
	u8 *dst, size_t dst_len, size_t *offset_io,
	const struct pkm_kunit_sid_attr_spec *entries, u32 count,
	u32 *offset_out);

int pkm_kunit_append_u32_section(u8 *dst, size_t dst_len,
					size_t *offset_io,
					const u32 *values, u32 count,
					u32 *offset_out);

size_t pkm_kunit_build_token_spec(
	u8 *dst, size_t dst_len, const struct pkm_kunit_token_spec_args *args);

void pkm_kunit_build_logon_sid(u64 session_id, u8 out[20]);

void pkm_kunit_build_args_v136(u8 *args);

size_t pkm_kunit_build_caap_spec(u8 *spec, const u8 *effective_dacl,
					u32 effective_dacl_len);

size_t pkm_kunit_build_caap_spec_with_staged_dacl(
	u8 *spec, const u8 *effective_dacl, u32 effective_dacl_len,
	const u8 *staged_dacl, u32 staged_dacl_len);

void pkm_kunit_build_read_control_args(u8 *args, s32 token_fd);

size_t pkm_kunit_build_read_control_sd(
	u8 *dst, size_t dst_len, const u8 *owner_sid, size_t owner_sid_len,
	const struct pkm_kunit_read_ace_spec *aces, size_t ace_count);

size_t pkm_kunit_build_null_dacl_sd(u8 *dst, size_t dst_len,
					   const u8 *owner_sid,
					   size_t owner_sid_len);

size_t pkm_kunit_build_confinement_object_sd(u8 *dst, size_t dst_len,
						    const u8 object_guid[16]);

size_t pkm_kunit_build_restrict_payload(
	u8 *payload,
	const u32 *deny_indices,
	size_t deny_count,
	const struct pkm_kacs_boot_group_view *restrict_sids,
	size_t sid_count);

long pkm_kunit_run_read_control_with_token_fd_summary(
	int token_fd, const u8 *sd, size_t sd_len, u32 *granted_out,
	struct pkm_kacs_ingress_summary *summary);

long pkm_kunit_run_read_control_with_token_fd(int token_fd, const u8 *sd,
						     size_t sd_len,
						     u32 *granted_out);

long pkm_kunit_create_confined_access_check_token(
	u64 privileges, struct pkm_kacs_token_fd_view *view);

long pkm_kunit_run_pip_labeled_sd_access_check(const u8 *sd,
						      size_t sd_len,
						      u32 arg_pip_type,
						      u32 arg_pip_trust,
						      u32 *granted);

long pkm_kunit_run_pip_labeled_access_check(u32 arg_pip_type,
						   u32 arg_pip_trust,
						   u32 *granted);

long pkm_kunit_run_caap_access_check(u32 *granted);

void pkm_kunit_build_access_system_args(u8 *args, s32 token_fd);

struct pkm_kmes_runtime_config pkm_kunit_kmes_default_config(void);

void pkm_kunit_expect_create_token_spec_einval(struct kunit *test,
						      const void *subject_token,
						      const u8 *spec,
						      size_t spec_len);

void pkm_kunit_expect_allow_caps_present(struct kunit *test,
						const struct cred *cred);

void pkm_kunit_expect_linux_cred_projection(struct kunit *test,
						   const struct cred *cred,
						   u32 uid, u32 gid);

void pkm_kunit_expect_process_state_snapshot_eq(
	struct kunit *test, const struct pkm_kacs_kunit_process_state_view *lhs,
	const struct pkm_kacs_kunit_process_state_view *rhs);

void pkm_kunit_signing_fill_blob(u8 blob[PKM_KUNIT_SIGNING_BLOB_LEN],
					u8 seed);

void pkm_kunit_signing_build_elf(
	u8 file[PKM_KUNIT_ELF_LEN],
	const u8 sig_blob[PKM_KUNIT_SIGNING_BLOB_LEN], bool include_sig_section,
	bool valid_sig_section);

void pkm_kunit_signing_fill_probe(
	struct pkm_kacs_kunit_signing_probe *probe);

void pkm_kunit_signing_fill_key(
	struct pkm_kacs_kunit_signing_key_entry *key, u8 seed, u32 pip_type,
	u32 pip_trust);

void pkm_kunit_signing_fill_tcb_vector_material(
	struct pkm_kacs_kunit_signing_probe *material);

int pkm_kunit_ed25519_crypto_verify(const u8 *public_key,
					   unsigned int public_key_len,
					   const u8 *msg, unsigned int msg_len,
					   const u8 *signature,
					   unsigned int signature_len);

int pkm_kunit_check_path_metadata_with_mask(u32 granted_mask, u32 op,
						   u32 mode, const char *name);

int pkm_kunit_check_path_metadata_with_foreign_everyone_mask(
	u32 granted_mask, u32 op, u32 mode, const char *name);

int pkm_kunit_check_inode_permission_with_mask(
	const void *subject_token, u32 granted_mask, int mask);

int pkm_kunit_check_inode_permission_with_mode(
	const void *subject_token, u32 granted_mask, u32 mode, int mask);

int pkm_kunit_namespace_parent_op(const void *subject_token,
					 u32 parent_mask, u32 op,
					 const u8 **created_sd_out,
					 size_t *created_sd_len_out);

int pkm_kunit_namespace_mknod_mode_op(const void *subject_token,
					     u32 parent_mask, umode_t mode,
					     const u8 **created_sd_out,
					     size_t *created_sd_len_out);

int pkm_kunit_namespace_link_op(const void *subject_token,
				       u32 source_mask, u32 parent_mask);

int pkm_kunit_namespace_delete_op(const void *subject_token,
					 u32 target_mask, u32 parent_mask,
					 u32 op, umode_t target_mode);

int pkm_kunit_namespace_rename_op(const void *subject_token,
					 u32 source_mask,
					 u32 old_parent_mask,
					 u32 new_parent_mask,
					 u32 target_mask,
					 bool target_present,
					 umode_t source_mode);

int pkm_kunit_namespace_readlink_op(const void *subject_token,
					   u32 source_mask);

int pkm_kunit_namespace_rename_flags_op(const void *subject_token,
					       u32 mount_policy,
					       u32 old_parent_mask,
					       unsigned int flags);

void pkm_kunit_expect_ioctl_access(
	struct kunit *test, const struct pkm_kunit_ioctl_expectation *entry);

void pkm_kunit_expect_proc_metadata_debug_bypass(
	struct kunit *test, u32 proc_mode);

void pkm_kunit_expect_proc_metadata_debug_pip_denial(
	struct kunit *test, u32 proc_mode);

const u8 *pkm_kunit_create_default_file_sd(const void *token,
						  size_t *len_out);

const u8 *pkm_kunit_create_query_only_file_sd(const void *token,
						     size_t *len_out);

const u8 *pkm_kunit_create_write_only_file_sd(const void *token,
						     size_t *len_out);

const u8 *pkm_kunit_create_file_sd_with_mandatory_resource_attr(
	const void *token, size_t *len_out);

const u8 *pkm_kunit_create_file_sd_with_mandatory_resource_attr_value(
	const void *token, u64 value, size_t *len_out);

const u8 *pkm_kunit_create_labeled_file_sd(const void *token,
						  u32 integrity_level,
						  size_t *len_out);

const u8 *pkm_kunit_create_labeled_audit_file_sd(
	const void *token, u32 integrity_level, size_t *len_out);

const u8 *pkm_kunit_create_precise_file_sd(const void *token,
						  u32 self_mask,
						  size_t *len_out);

const u8 *pkm_kunit_synthesize_file_sd(const u8 *parent_sd,
					      size_t parent_sd_len,
					      const u8 *template_sd,
					      size_t template_sd_len,
					      u32 child_is_directory,
					      size_t *len_out);

const u8 *pkm_kunit_first_dacl_ace_const(const u8 *sd_bytes);

const u8 *pkm_kunit_first_sacl_ace_const(const u8 *sd_bytes);

u8 *pkm_kunit_first_dacl_ace(u8 *sd_bytes);

const u8 *pkm_kunit_first_inherited_dacl_ace_const(const u8 *sd_bytes);

const u8 *pkm_kunit_first_inherited_sacl_ace_const(const u8 *sd_bytes);

void pkm_kunit_make_first_file_ace_inheritable(u8 *sd_bytes,
						      u8 inherit_flags);

void pkm_kunit_make_first_file_ace_mask(u8 *sd_bytes, u32 mask);

void pkm_kunit_make_first_sacl_ace_inheritable(u8 *sd_bytes,
						      u8 inherit_flags);

void pkm_kunit_make_first_file_ace_opaque(u8 *sd_bytes, u8 ace_flags);

void pkm_kunit_make_first_file_ace_sid(u8 *sd_bytes, const u8 *sid,
					      size_t sid_len);

long pkm_kunit_create_condition_token_ex(
	bool with_device_group, bool with_user_claim, bool with_device_claim,
	const struct pkm_kunit_sid_attr_spec *restricted_sids,
	u32 restricted_sid_count,
	const struct pkm_kunit_sid_attr_spec *restricted_device_groups,
	u32 restricted_device_group_count,
	struct pkm_kacs_token_fd_view *view);

long pkm_kunit_create_condition_token(
	bool with_device_group, bool with_user_claim, bool with_device_claim,
	const struct pkm_kunit_sid_attr_spec *restricted_device_groups,
	u32 restricted_device_group_count,
	struct pkm_kacs_token_fd_view *view);

long pkm_kunit_create_device_condition_token(
	bool with_device_group, struct pkm_kacs_token_fd_view *view);

void pkm_kunit_expect_native_overwrite_identity(struct kunit *test,
						       u32 create_disposition);

void pkm_kunit_expect_native_create_owner_success(
	struct kunit *test, const void *subject_token, const u8 *owner_sid,
	size_t owner_sid_len);

void pkm_kunit_expect_get_sd_syscall_copyout(
	struct kunit *test, int fd, const u8 *expected, size_t expected_len,
	u32 security_info);

void pkm_kunit_expect_mount_policy_failure_preserves_state(
	struct kunit *test, const void *subject_token,
	const struct kacs_mount_policy_args *initial_args,
	const struct kacs_mount_policy_args *failure_args,
	long expected_failure_ret, u32 expected_template_len);

void pkm_kunit_expect_inherited_ace_flags(struct kunit *test,
						 const u8 *sd_bytes,
						 bool expect_inherited,
						 u8 expected_flags);

void pkm_kunit_expect_inherited_sacl_ace_flags(struct kunit *test,
						      const u8 *sd_bytes,
						      bool expect_inherited,
						      u8 expected_flags);

int pkm_kunit_open_current_pidfd(void);

void pkm_kunit_expect_default_process_sd_shape(
	struct kunit *test, const u8 *process_sd, size_t process_sd_len,
	const struct pkm_kacs_boot_snapshot *snapshot);

void pkm_kunit_expect_impersonation_gate(
	struct kunit *test,
	const struct pkm_kunit_impersonation_gate_case *gate_case);

void pkm_kunit_expect_token_own_sd_valid(struct kunit *test,
						const void *token);

void pkm_kunit_expect_access_check_list_input_denied(
	struct kunit *test, u8 *object_tree, size_t object_tree_len,
	u64 object_tree_ptr, u32 object_tree_count, u32 results_count);

#endif /* PKM_KACS_KUNIT_COMMON_H */
